#!/usr/bin/env python3
"""Generate the bundled Honolulu route and local context pack for Cruisin."""

from __future__ import annotations

import json
import re
import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RESOURCE_DIR = ROOT / "Cruisin"


FACTS = [
    {
        "id": "area-waikiki",
        "name": "Waikiki",
        "category": "area",
        "latitude": 21.2793,
        "longitude": -157.8293,
        "narration": "You are entering Waikiki, the dense beachfront district that turned Honolulu into a global visitor hub.",
        "sourceName": "Wikipedia",
        "sourceURL": "https://en.wikipedia.org/wiki/Waikiki",
        "priority": 5,
    },
    {
        "id": "poi-duke-kahanamoku-statue",
        "name": "Duke Kahanamoku Statue",
        "category": "culture",
        "latitude": 21.2767,
        "longitude": -157.8257,
        "narration": "The Duke Kahanamoku statue honors the Olympic swimmer and surfer who helped introduce modern surfing to the world.",
        "sourceName": "Go Hawaii",
        "sourceURL": "https://www.gohawaii.com/islands/oahu/regions/honolulu/duke-kahanamoku-statue",
        "priority": 5,
    },
    {
        "id": "poi-waikiki-beach",
        "name": "Waikiki Beach",
        "category": "landmark",
        "latitude": 21.2766,
        "longitude": -157.8268,
        "narration": "Waikiki Beach is a short, famous sweep of sand backed by hotels, surf breaks, and Diamond Head views.",
        "sourceName": "Wikipedia",
        "sourceURL": "https://en.wikipedia.org/wiki/Waikiki_Beach",
        "priority": 5,
    },
    {
        "id": "poi-moana-surfrider",
        "name": "Moana Surfrider",
        "category": "history",
        "latitude": 21.2769,
        "longitude": -157.8278,
        "narration": "The Moana Surfrider opened in 1901 and is often called the First Lady of Waikiki.",
        "sourceName": "Historic Hotels of America",
        "sourceURL": "https://www.historichotels.org/us/hotels-resorts/moana-surfrider-a-westin-resort-and-spa/",
        "priority": 4,
    },
    {
        "id": "poi-royal-hawaiian-hotel",
        "name": "Royal Hawaiian Hotel",
        "category": "history",
        "latitude": 21.2776,
        "longitude": -157.8296,
        "narration": "The pink Royal Hawaiian Hotel opened in 1927 and became one of Waikiki's most recognizable landmarks.",
        "sourceName": "Wikipedia",
        "sourceURL": "https://en.wikipedia.org/wiki/Royal_Hawaiian_Hotel",
        "priority": 4,
    },
    {
        "id": "poi-international-market-place",
        "name": "International Market Place",
        "category": "landmark",
        "latitude": 21.2794,
        "longitude": -157.8267,
        "narration": "International Market Place sits around a large banyan tree and marks a long-running retail crossroads in Waikiki.",
        "sourceName": "International Market Place",
        "sourceURL": "https://shopinternationalmarketplace.com/",
        "priority": 3,
    },
    {
        "id": "poi-honolulu-zoo",
        "name": "Honolulu Zoo",
        "category": "nature",
        "latitude": 21.2715,
        "longitude": -157.8213,
        "narration": "Honolulu Zoo anchors the Diamond Head end of Waikiki near Kapiolani Park.",
        "sourceName": "Honolulu Zoo",
        "sourceURL": "https://www.honoluluzoo.org/",
        "priority": 3,
    },
    {
        "id": "poi-kapiolani-park",
        "name": "Kapiolani Park",
        "category": "nature",
        "latitude": 21.2686,
        "longitude": -157.8193,
        "narration": "Kapiolani Park is Honolulu's oldest public park and a green buffer between Waikiki and Diamond Head.",
        "sourceName": "City and County of Honolulu",
        "sourceURL": "https://www.honolulu.gov/parks/",
        "priority": 3,
    },
    {
        "id": "poi-waikiki-aquarium",
        "name": "Waikiki Aquarium",
        "category": "nature",
        "latitude": 21.2657,
        "longitude": -157.8213,
        "narration": "Waikiki Aquarium has focused on Pacific marine life beside the reef since the early twentieth century.",
        "sourceName": "Waikiki Aquarium",
        "sourceURL": "https://www.waikikiaquarium.org/",
        "priority": 3,
    },
    {
        "id": "poi-diamond-head",
        "name": "Diamond Head",
        "category": "lookout",
        "latitude": 21.2619,
        "longitude": -157.8059,
        "narration": "Diamond Head is the volcanic tuff cone framing Waikiki's eastern skyline.",
        "sourceName": "Hawaii State Parks",
        "sourceURL": "https://dlnr.hawaii.gov/dsp/parks/oahu/diamond-head-state-monument/",
        "priority": 5,
    },
    {
        "id": "poi-ala-wai-canal",
        "name": "Ala Wai Canal",
        "category": "landmark",
        "latitude": 21.2875,
        "longitude": -157.8346,
        "narration": "The Ala Wai Canal separates Waikiki from inland Honolulu and reshaped this former wetland district.",
        "sourceName": "Wikipedia",
        "sourceURL": "https://en.wikipedia.org/wiki/Ala_Wai_Canal",
        "priority": 4,
    },
    {
        "id": "poi-fort-derussy",
        "name": "Fort DeRussy",
        "category": "history",
        "latitude": 21.2799,
        "longitude": -157.8349,
        "narration": "Fort DeRussy is a military reservation and beach park that preserves a rare open stretch inside Waikiki.",
        "sourceName": "Wikipedia",
        "sourceURL": "https://en.wikipedia.org/wiki/Fort_DeRussy",
        "priority": 3,
    },
    {
        "id": "poi-army-museum-hawaii",
        "name": "U.S. Army Museum of Hawaii",
        "category": "history",
        "latitude": 21.2785,
        "longitude": -157.8336,
        "narration": "The U.S. Army Museum of Hawaii occupies Battery Randolph at Fort DeRussy.",
        "sourceName": "U.S. Army Museum of Hawaii",
        "sourceURL": "https://hiarmymuseumsoc.org/",
        "priority": 3,
    },
    {
        "id": "poi-hawaii-convention-center",
        "name": "Hawaii Convention Center",
        "category": "landmark",
        "latitude": 21.2901,
        "longitude": -157.8355,
        "narration": "The Hawaii Convention Center uses open-air architecture to catch trade winds near the edge of Waikiki.",
        "sourceName": "Hawaii Convention Center",
        "sourceURL": "https://www.hawaiiconvention.com/",
        "priority": 3,
    },
    {
        "id": "area-ala-moana",
        "name": "Ala Moana",
        "category": "area",
        "latitude": 21.2902,
        "longitude": -157.8436,
        "narration": "Ala Moana means path to the sea, and this district links shopping, beach park, and harbor edges.",
        "sourceName": "Wikipedia",
        "sourceURL": "https://en.wikipedia.org/wiki/Ala_Moana",
        "priority": 5,
    },
    {
        "id": "poi-ala-moana-center",
        "name": "Ala Moana Center",
        "category": "landmark",
        "latitude": 21.2915,
        "longitude": -157.8430,
        "narration": "Ala Moana Center is one of the world's largest open-air shopping centers.",
        "sourceName": "Ala Moana Center",
        "sourceURL": "https://www.alamoanacenter.com/",
        "priority": 4,
    },
    {
        "id": "poi-ala-moana-beach-park",
        "name": "Ala Moana Beach Park",
        "category": "nature",
        "latitude": 21.2849,
        "longitude": -157.8466,
        "narration": "Ala Moana Beach Park is a local favorite with calm water protected by an outer reef.",
        "sourceName": "City and County of Honolulu",
        "sourceURL": "https://www.honolulu.gov/parks/",
        "priority": 4,
    },
    {
        "id": "poi-magic-island",
        "name": "Magic Island",
        "category": "lookout",
        "latitude": 21.2842,
        "longitude": -157.8475,
        "narration": "Magic Island is a man-made peninsula with wide views back toward Waikiki and Diamond Head.",
        "sourceName": "Wikipedia",
        "sourceURL": "https://en.wikipedia.org/wiki/Magic_Island_(Hawaii)",
        "priority": 4,
    },
    {
        "id": "poi-yacht-harbor",
        "name": "Ala Wai Small Boat Harbor",
        "category": "landmark",
        "latitude": 21.2836,
        "longitude": -157.8395,
        "narration": "Ala Wai Small Boat Harbor sits between Waikiki and Ala Moana with one of Honolulu's busiest marina edges.",
        "sourceName": "Hawaii Division of Boating and Ocean Recreation",
        "sourceURL": "https://dlnr.hawaii.gov/dobor/ala-wai-small-boat-harbor/",
        "priority": 3,
    },
    {
        "id": "area-kakaako",
        "name": "Kakaako",
        "category": "area",
        "latitude": 21.2983,
        "longitude": -157.8576,
        "narration": "You are entering Kakaako, a former industrial district now known for murals, towers, restaurants, and waterfront parks.",
        "sourceName": "Wikipedia",
        "sourceURL": "https://en.wikipedia.org/wiki/Kaka%CA%BBako",
        "priority": 5,
    },
    {
        "id": "poi-ward-village",
        "name": "Ward Village",
        "category": "landmark",
        "latitude": 21.2947,
        "longitude": -157.8527,
        "narration": "Ward Village is a large mixed-use redevelopment reshaping the center of Kakaako.",
        "sourceName": "Ward Village",
        "sourceURL": "https://www.wardvillage.com/",
        "priority": 3,
    },
    {
        "id": "poi-salt-kakaako",
        "name": "SALT at Our Kakaako",
        "category": "food",
        "latitude": 21.2972,
        "longitude": -157.8610,
        "narration": "SALT at Our Kakaako clusters local food, coffee, shops, and public art in converted warehouse blocks.",
        "sourceName": "SALT at Our Kakaako",
        "sourceURL": "https://saltatkakaako.com/",
        "priority": 4,
    },
    {
        "id": "poi-kakaako-waterfront-park",
        "name": "Kakaako Waterfront Park",
        "category": "lookout",
        "latitude": 21.2951,
        "longitude": -157.8680,
        "narration": "Kakaako Waterfront Park has grassy hills and broad harbor views where industrial Honolulu meets the ocean.",
        "sourceName": "Hawaii Community Development Authority",
        "sourceURL": "https://dbedt.hawaii.gov/hcda/",
        "priority": 4,
    },
    {
        "id": "poi-kewalo-basin",
        "name": "Kewalo Basin Harbor",
        "category": "landmark",
        "latitude": 21.2896,
        "longitude": -157.8585,
        "narration": "Kewalo Basin Harbor is a working harbor for tour boats and fishing vessels at the edge of Kakaako.",
        "sourceName": "Kewalo Harbor",
        "sourceURL": "https://www.kewaloharbor.com/",
        "priority": 3,
    },
    {
        "id": "poi-mother-waldron-park",
        "name": "Mother Waldron Neighborhood Park",
        "category": "nature",
        "latitude": 21.2976,
        "longitude": -157.8596,
        "narration": "Mother Waldron Park is a neighborhood green space tucked inside Kakaako's fast-changing street grid.",
        "sourceName": "City and County of Honolulu",
        "sourceURL": "https://www.honolulu.gov/parks/",
        "priority": 2,
    },
    {
        "id": "poi-hawaii-childrens-discovery-center",
        "name": "Hawaii Children's Discovery Center",
        "category": "culture",
        "latitude": 21.2928,
        "longitude": -157.8634,
        "narration": "The Hawaii Children's Discovery Center sits near the waterfront with hands-on exhibits for families.",
        "sourceName": "Hawaii Children's Discovery Center",
        "sourceURL": "https://discoverycenterhawaii.org/",
        "priority": 2,
    },
    {
        "id": "poi-honolulu-museum-of-art",
        "name": "Honolulu Museum of Art",
        "category": "culture",
        "latitude": 21.3046,
        "longitude": -157.8489,
        "narration": "Honolulu Museum of Art connects Asian, Pacific, European, and American collections in a compact campus.",
        "sourceName": "Honolulu Museum of Art",
        "sourceURL": "https://honolulumuseum.org/",
        "priority": 4,
    },
    {
        "id": "poi-thomas-square",
        "name": "Thomas Square",
        "category": "history",
        "latitude": 21.3047,
        "longitude": -157.8509,
        "narration": "Thomas Square commemorates the 1843 restoration of the Hawaiian Kingdom's sovereignty.",
        "sourceName": "Wikipedia",
        "sourceURL": "https://en.wikipedia.org/wiki/Thomas_Square",
        "priority": 4,
    },
    {
        "id": "poi-blaisdell-center",
        "name": "Neal S. Blaisdell Center",
        "category": "culture",
        "latitude": 21.3009,
        "longitude": -157.8508,
        "narration": "The Blaisdell Center is Honolulu's major arena, concert hall, and exhibition complex.",
        "sourceName": "Neal S. Blaisdell Center",
        "sourceURL": "https://blaisdellcenter.com/",
        "priority": 3,
    },
    {
        "id": "area-civic-center",
        "name": "Capitol District",
        "category": "area",
        "latitude": 21.3068,
        "longitude": -157.8576,
        "narration": "You are entering Honolulu's civic core, where the palace, capitol, courts, and city hall sit within a few blocks.",
        "sourceName": "Wikipedia",
        "sourceURL": "https://en.wikipedia.org/wiki/Hawaii_Capital_Historic_District",
        "priority": 5,
    },
    {
        "id": "poi-iolani-palace",
        "name": "Iolani Palace",
        "category": "history",
        "latitude": 21.3069,
        "longitude": -157.8583,
        "narration": "Iolani Palace was the royal residence of the Hawaiian Kingdom and is the only official royal palace in the United States.",
        "sourceName": "Iolani Palace",
        "sourceURL": "https://www.iolanipalace.org/",
        "priority": 5,
    },
    {
        "id": "poi-king-kamehameha-statue",
        "name": "King Kamehameha Statue",
        "category": "history",
        "latitude": 21.3055,
        "longitude": -157.8589,
        "narration": "The King Kamehameha statue stands in front of Aliiolani Hale facing Iolani Palace.",
        "sourceName": "Wikipedia",
        "sourceURL": "https://en.wikipedia.org/wiki/Statues_of_Kamehameha_I",
        "priority": 4,
    },
    {
        "id": "poi-aliiolani-hale",
        "name": "Aliiolani Hale",
        "category": "history",
        "latitude": 21.3054,
        "longitude": -157.8587,
        "narration": "Aliiolani Hale houses the Hawaii State Supreme Court and anchors one side of the palace grounds.",
        "sourceName": "Hawaii State Judiciary",
        "sourceURL": "https://www.courts.state.hi.us/",
        "priority": 4,
    },
    {
        "id": "poi-hawaii-state-capitol",
        "name": "Hawaii State Capitol",
        "category": "landmark",
        "latitude": 21.3075,
        "longitude": -157.8570,
        "narration": "The Hawaii State Capitol uses reflecting pools and open forms to reference the islands, ocean, and volcanoes.",
        "sourceName": "Wikipedia",
        "sourceURL": "https://en.wikipedia.org/wiki/Hawaii_State_Capitol",
        "priority": 4,
    },
    {
        "id": "poi-kawaiahao-church",
        "name": "Kawaiahao Church",
        "category": "history",
        "latitude": 21.3043,
        "longitude": -157.8595,
        "narration": "Kawaiahao Church was built from coral blocks and is closely tied to nineteenth-century Honolulu.",
        "sourceName": "Kawaiahao Church",
        "sourceURL": "https://www.kawaiahao.org/",
        "priority": 4,
    },
    {
        "id": "poi-honolulu-hale",
        "name": "Honolulu Hale",
        "category": "landmark",
        "latitude": 21.3047,
        "longitude": -157.8584,
        "narration": "Honolulu Hale is the city hall for the City and County of Honolulu.",
        "sourceName": "City and County of Honolulu",
        "sourceURL": "https://www.honolulu.gov/",
        "priority": 3,
    },
    {
        "id": "poi-hawaiian-mission-houses",
        "name": "Hawaiian Mission Houses",
        "category": "history",
        "latitude": 21.3041,
        "longitude": -157.8603,
        "narration": "The Hawaiian Mission Houses preserve some of Honolulu's oldest Western-style buildings.",
        "sourceName": "Hawaiian Mission Houses",
        "sourceURL": "https://missionhouses.org/",
        "priority": 3,
    },
    {
        "id": "poi-washington-place",
        "name": "Washington Place",
        "category": "history",
        "latitude": 21.3097,
        "longitude": -157.8570,
        "narration": "Washington Place was Queen Liliuokalani's home and later served as Hawaii's governor's residence.",
        "sourceName": "Washington Place Foundation",
        "sourceURL": "https://washingtonplacefoundation.org/",
        "priority": 3,
    },
    {
        "id": "poi-state-library",
        "name": "Hawaii State Library",
        "category": "culture",
        "latitude": 21.3062,
        "longitude": -157.8565,
        "narration": "The Hawaii State Library faces the capitol district from a historic Beaux-Arts building.",
        "sourceName": "Hawaii State Public Library System",
        "sourceURL": "https://www.librarieshawaii.org/branch/hawaii-state-library/",
        "priority": 2,
    },
    {
        "id": "poi-punchbowl",
        "name": "National Memorial Cemetery of the Pacific",
        "category": "lookout",
        "latitude": 21.3121,
        "longitude": -157.8466,
        "narration": "Punchbowl crater holds the National Memorial Cemetery of the Pacific and a sweeping view over Honolulu.",
        "sourceName": "National Cemetery Administration",
        "sourceURL": "https://www.cem.va.gov/cems/nchp/nmcp.asp",
        "priority": 4,
    },
    {
        "id": "poi-aloha-tower",
        "name": "Aloha Tower",
        "category": "history",
        "latitude": 21.3069,
        "longitude": -157.8657,
        "narration": "Aloha Tower opened in 1926 as a harbor landmark greeting passengers arriving by ship.",
        "sourceName": "Wikipedia",
        "sourceURL": "https://en.wikipedia.org/wiki/Aloha_Tower",
        "priority": 4,
    },
    {
        "id": "poi-honolulu-harbor",
        "name": "Honolulu Harbor",
        "category": "landmark",
        "latitude": 21.3061,
        "longitude": -157.8702,
        "narration": "Honolulu Harbor is the state's main commercial harbor and has shaped the city since the monarchy era.",
        "sourceName": "Hawaii Department of Transportation",
        "sourceURL": "https://hidot.hawaii.gov/harbors/",
        "priority": 3,
    },
    {
        "id": "area-chinatown",
        "name": "Chinatown",
        "category": "area",
        "latitude": 21.3114,
        "longitude": -157.8625,
        "narration": "You are entering Chinatown, one of Honolulu's oldest business districts and a dense food and arts neighborhood.",
        "sourceName": "Wikipedia",
        "sourceURL": "https://en.wikipedia.org/wiki/Chinatown,_Honolulu",
        "priority": 5,
    },
    {
        "id": "poi-hawaii-theatre",
        "name": "Hawaii Theatre",
        "category": "culture",
        "latitude": 21.3119,
        "longitude": -157.8623,
        "narration": "Hawaii Theatre opened in 1922 and remains a major restored performing arts venue downtown.",
        "sourceName": "Hawaii Theatre Center",
        "sourceURL": "https://www.hawaiitheatre.com/",
        "priority": 4,
    },
    {
        "id": "poi-foster-botanical-garden",
        "name": "Foster Botanical Garden",
        "category": "nature",
        "latitude": 21.3160,
        "longitude": -157.8587,
        "narration": "Foster Botanical Garden preserves tropical trees and plants in the middle of urban Honolulu.",
        "sourceName": "Honolulu Botanical Gardens",
        "sourceURL": "https://www.honolulu.gov/parks/hbg/",
        "priority": 3,
    },
    {
        "id": "poi-liliuokalani-botanical-garden",
        "name": "Liliuokalani Botanical Garden",
        "category": "nature",
        "latitude": 21.3187,
        "longitude": -157.8554,
        "narration": "Liliuokalani Botanical Garden focuses on native Hawaiian plants and a stream-fed urban landscape.",
        "sourceName": "Honolulu Botanical Gardens",
        "sourceURL": "https://www.honolulu.gov/parks/hbg/",
        "priority": 3,
    },
    {
        "id": "poi-murphy-bar",
        "name": "Murphy's Bar and Grill",
        "category": "food",
        "latitude": 21.3104,
        "longitude": -157.8623,
        "narration": "Murphy's occupies a historic downtown corner and is a familiar Chinatown-adjacent lunch and pau hana stop.",
        "sourceName": "Murphy's Bar and Grill",
        "sourceURL": "https://www.murphyshawaii.com/",
        "priority": 2,
    },
    {
        "id": "poi-the-pig-and-the-lady",
        "name": "The Pig and the Lady",
        "category": "food",
        "latitude": 21.3126,
        "longitude": -157.8618,
        "narration": "The Pig and the Lady helped make Chinatown a modern Honolulu dining destination.",
        "sourceName": "The Pig and the Lady",
        "sourceURL": "https://thepigandthelady.com/",
        "priority": 3,
    },
    {
        "id": "poi-maguro-brothers-chinatown",
        "name": "Maguro Brothers Chinatown",
        "category": "food",
        "latitude": 21.3125,
        "longitude": -157.8612,
        "narration": "Maguro Brothers is known for sashimi and poke from a small Chinatown market counter.",
        "sourceName": "Maguro Brothers Hawaii",
        "sourceURL": "https://www.magurobrothershawaii.com/",
        "priority": 2,
    },
    {
        "id": "poi-leonards-bakery",
        "name": "Leonard's Bakery",
        "category": "food",
        "latitude": 21.2849,
        "longitude": -157.8135,
        "narration": "Leonard's Bakery is famous for malasadas, the Portuguese-style doughnuts that became a Honolulu staple.",
        "sourceName": "Leonard's Bakery",
        "sourceURL": "https://www.leonardshawaii.com/",
        "priority": 3,
    },
    {
        "id": "poi-rainbow-drive-in",
        "name": "Rainbow Drive-In",
        "category": "food",
        "latitude": 21.2774,
        "longitude": -157.8134,
        "narration": "Rainbow Drive-In is a plate-lunch institution near the Diamond Head side of Waikiki.",
        "sourceName": "Rainbow Drive-In",
        "sourceURL": "https://rainbowdrivein.com/",
        "priority": 3,
    },
    {
        "id": "poi-marugame-udon-waikiki",
        "name": "Marugame Udon Waikiki",
        "category": "food",
        "latitude": 21.2796,
        "longitude": -157.8266,
        "narration": "Marugame Udon's Waikiki shop is known for fast cafeteria-style noodles and frequent lines.",
        "sourceName": "Marugame Udon USA",
        "sourceURL": "https://www.marugameudon.com/",
        "priority": 2,
    },
    {
        "id": "poi-liliha-bakery",
        "name": "Liliha Bakery",
        "category": "food",
        "latitude": 21.3167,
        "longitude": -157.8483,
        "narration": "Liliha Bakery is known for coco puffs and local diner comfort food.",
        "sourceName": "Liliha Bakery",
        "sourceURL": "https://www.lilihabakery.com/",
        "priority": 2,
    },
    {
        "id": "poi-highway-inn-kakaako",
        "name": "Highway Inn Kakaako",
        "category": "food",
        "latitude": 21.2973,
        "longitude": -157.8611,
        "narration": "Highway Inn's Kakaako location serves Hawaiian food in the middle of the neighborhood's restaurant cluster.",
        "sourceName": "Highway Inn",
        "sourceURL": "https://www.myhighwayinn.com/",
        "priority": 3,
    },
    {
        "id": "poi-side-street-inn",
        "name": "Side Street Inn",
        "category": "food",
        "latitude": 21.2956,
        "longitude": -157.8364,
        "narration": "Side Street Inn is a local comfort-food spot known for share plates and after-work gatherings.",
        "sourceName": "Side Street Inn",
        "sourceURL": "https://sidestreetinn.com/",
        "priority": 2,
    },
    {
        "id": "poi-bishop-museum",
        "name": "Bishop Museum",
        "category": "culture",
        "latitude": 21.3339,
        "longitude": -157.8708,
        "narration": "Bishop Museum is Hawaii's major museum for natural history and Hawaiian and Pacific culture.",
        "sourceName": "Bishop Museum",
        "sourceURL": "https://www.bishopmuseum.org/",
        "priority": 3,
    },
    {
        "id": "poi-queen-emma-summer-palace",
        "name": "Queen Emma Summer Palace",
        "category": "history",
        "latitude": 21.3665,
        "longitude": -157.7934,
        "narration": "Queen Emma Summer Palace preserves a mountain-side royal retreat above Honolulu.",
        "sourceName": "Daughters of Hawaii",
        "sourceURL": "https://daughtersofhawaii.org/",
        "priority": 2,
    },
    {
        "id": "poi-tantalus-lookout",
        "name": "Tantalus Lookout",
        "category": "lookout",
        "latitude": 21.3157,
        "longitude": -157.8180,
        "narration": "Tantalus Lookout gives a high, sweeping view over Diamond Head, Waikiki, downtown, and the harbor.",
        "sourceName": "Hawaii State Parks",
        "sourceURL": "https://dlnr.hawaii.gov/dsp/parks/oahu/puu-ualakaa-state-wayside/",
        "priority": 3,
    },
    {
        "id": "poi-manoa-falls",
        "name": "Manoa Falls Trail",
        "category": "nature",
        "latitude": 21.3330,
        "longitude": -157.8009,
        "narration": "Manoa Falls Trail leads through a rainforest valley to one of Honolulu's most visited waterfalls.",
        "sourceName": "Hawaii Trails",
        "sourceURL": "https://hawaiitrails.hawaii.gov/trails/",
        "priority": 2,
    },
    {
        "id": "poi-shangri-la",
        "name": "Shangri La Museum of Islamic Art",
        "category": "culture",
        "latitude": 21.2552,
        "longitude": -157.7872,
        "narration": "Shangri La is Doris Duke's oceanfront home and a museum of Islamic art near Diamond Head.",
        "sourceName": "Shangri La",
        "sourceURL": "https://www.shangrilahawaii.org/",
        "priority": 2,
    },
    {
        "id": "poi-sans-souci-beach",
        "name": "Sans Souci Beach",
        "category": "nature",
        "latitude": 21.2649,
        "longitude": -157.8204,
        "narration": "Sans Souci Beach is a calmer swimming and snorkeling pocket near the Waikiki Aquarium.",
        "sourceName": "City and County of Honolulu",
        "sourceURL": "https://www.honolulu.gov/parks/",
        "priority": 2,
    },
    {
        "id": "poi-royal-mausoleum",
        "name": "Royal Mausoleum at Mauna Ala",
        "category": "history",
        "latitude": 21.3263,
        "longitude": -157.8473,
        "narration": "Mauna Ala is the Royal Mausoleum, resting place for many members of Hawaiian royal families.",
        "sourceName": "Hawaii State Parks",
        "sourceURL": "https://dlnr.hawaii.gov/dsp/parks/oahu/royal-mausoleum-state-monument/",
        "priority": 2,
    },
    {
        "id": "poi-japanese-cultural-center",
        "name": "Japanese Cultural Center of Hawaii",
        "category": "culture",
        "latitude": 21.2941,
        "longitude": -157.8190,
        "narration": "The Japanese Cultural Center of Hawaii preserves stories of Japanese immigration and community life in the islands.",
        "sourceName": "Japanese Cultural Center of Hawaii",
        "sourceURL": "https://www.jcch.com/",
        "priority": 2,
    },
    {
        "id": "poi-university-hawaii-manoa",
        "name": "University of Hawaii at Manoa",
        "category": "landmark",
        "latitude": 21.2969,
        "longitude": -157.8171,
        "narration": "The University of Hawaii at Manoa sits in the valley behind Waikiki and is the flagship public university campus.",
        "sourceName": "University of Hawaii at Manoa",
        "sourceURL": "https://manoa.hawaii.edu/",
        "priority": 2,
    },
    {
        "id": "poi-chaminade-university",
        "name": "Chaminade University",
        "category": "landmark",
        "latitude": 21.2902,
        "longitude": -157.8079,
        "narration": "Chaminade University occupies a hillside campus above Kaimuki with broad views toward Honolulu.",
        "sourceName": "Chaminade University",
        "sourceURL": "https://chaminade.edu/",
        "priority": 1,
    },
]

KALAKAUA_WAIKIKI_FACTS = [
    {
        "id": "poi-king-kalakaua-statue-waikiki-gateway",
        "name": "King David Kalakaua Statue",
        "category": "culture",
        "subcategory": "public_art",
        "tags": ["kalakaua-avenue", "statue", "monarchy", "gateway"],
        "latitude": 21.2855,
        "longitude": -157.8329,
        "narration": "The route begins near the Kalakaua statue, a gateway marker for the avenue named after Hawaii's last reigning king.",
        "sourceName": "Historic Hawaii Foundation",
        "sourceURL": "https://historichawaii.org/2022/07/22/photos-from-the-statues-of-waikiki-walking-tour/",
        "priority": 4,
        "onKalakaua": True,
        "onWaikikiBeach": False,
        "addressOrFrontage": "2050 Kalakaua Ave / Waikiki Gateway Park",
        "scopeDecision": "keep",
        "scopeNotes": "At the Ala Moana Boulevard/Kalakaua Avenue route start.",
    },
    {
        "id": "poi-luxury-row",
        "name": "Luxury Row",
        "category": "landmark",
        "subcategory": "retail",
        "tags": ["kalakaua-avenue", "retail", "street-life"],
        "latitude": 21.2827,
        "longitude": -157.8314,
        "narration": "Luxury Row condenses Kalakaua's high-end storefront identity into a compact block of international fashion brands.",
        "sourceName": "Luxury Row",
        "sourceURL": "https://shopluxuryrow.com/",
        "priority": 2,
        "onKalakaua": True,
        "onWaikikiBeach": False,
        "addressOrFrontage": "2100 Kalakaua Ave",
        "scopeDecision": "keep",
        "scopeNotes": "Official Kalakaua Avenue frontage.",
    },
    {
        "id": "poi-royal-hawaiian-center-helumoa",
        "name": "Royal Hawaiian Center / Helumoa",
        "category": "culture",
        "subcategory": "historic_place",
        "tags": ["kalakaua-avenue", "helumoa", "royal-history", "retail"],
        "latitude": 21.27948,
        "longitude": -157.830062,
        "narration": "Royal Hawaiian Center sits on Helumoa, the historic coconut-grove landscape now folded into Kalakaua's retail core.",
        "sourceName": "Royal Hawaiian Center",
        "sourceURL": "https://www.royalhawaiiancenter.com/heritage",
        "sourceURLs": [
            "https://www.royalhawaiiancenter.com/heritage",
            "https://www.royalhawaiiancenter.com/centerinfo/",
        ],
        "priority": 5,
        "onKalakaua": True,
        "onWaikikiBeach": False,
        "addressOrFrontage": "2201 Kalakaua Ave",
        "scopeDecision": "keep",
        "scopeNotes": "Kalakaua frontage; heritage source ties the site to Helumoa.",
    },
    {
        "id": "poi-sheraton-waikiki",
        "name": "Sheraton Waikiki Beach Resort",
        "category": "landmark",
        "subcategory": "hotel_architecture",
        "tags": ["kalakaua-avenue", "beachfront", "hotel", "architecture"],
        "latitude": 21.27762,
        "longitude": -157.830245,
        "narration": "Sheraton Waikiki is a 1971 beachfront high-rise that once ranked among the world's largest resort hotels.",
        "sourceName": "SAH Archipedia",
        "sourceURL": "https://sah-archipedia.org/buildings/HI-01-OA136",
        "priority": 3,
        "onKalakaua": True,
        "onWaikikiBeach": True,
        "addressOrFrontage": "2255 Kalakaua Ave",
        "scopeDecision": "keep",
        "scopeNotes": "Official Kalakaua address and direct Waikiki Beach frontage.",
    },
    {
        "id": "poi-royal-hawaiian-hotel",
        "name": "The Royal Hawaiian",
        "category": "history",
        "subcategory": "historic_hotel",
        "tags": ["kalakaua-avenue", "beachfront", "hotel", "pink-palace"],
        "latitude": 21.277333,
        "longitude": -157.828968,
        "narration": "The Royal Hawaiian opened in 1927 and made its pink beachfront profile one of Waikiki's defining landmarks.",
        "sourceName": "The Royal Hawaiian",
        "sourceURL": "https://www.royal-hawaiian.com/history-overview/",
        "sourceURLs": [
            "https://www.royal-hawaiian.com/history-overview/",
            "https://historichawaii.org/historic-property-oa/royal-hawaiian-hotel/",
        ],
        "priority": 5,
        "onKalakaua": True,
        "onWaikikiBeach": True,
        "addressOrFrontage": "2259 Kalakaua Ave",
        "scopeDecision": "keep",
        "scopeNotes": "Historic Kalakaua hotel with Waikiki Beach frontage.",
    },
    {
        "id": "poi-waikiki-shopping-plaza",
        "name": "Waikiki Shopping Plaza",
        "category": "landmark",
        "subcategory": "retail",
        "tags": ["kalakaua-avenue", "retail", "seaside-avenue"],
        "latitude": 21.2793,
        "longitude": -157.8285,
        "narration": "Waikiki Shopping Plaza has marked the Kalakaua and Seaside retail corner since 1978.",
        "sourceName": "Waikiki Shopping Plaza",
        "sourceURL": "https://waikikishoppingplaza.com/about/",
        "priority": 2,
        "onKalakaua": True,
        "onWaikikiBeach": False,
        "addressOrFrontage": "2250 Kalakaua Ave",
        "scopeDecision": "keep",
        "scopeNotes": "Kalakaua/Seaside corner on the route.",
    },
    {
        "id": "poi-waikiki-theatre-site",
        "name": "Waikiki Theatre Site",
        "category": "history",
        "subcategory": "lost_building",
        "tags": ["kalakaua-avenue", "architecture", "theater", "lost-waikiki"],
        "latitude": 21.278533,
        "longitude": -157.827943,
        "narration": "The former Waikiki Theatre was a 1936 atmospheric movie palace with artificial clouds, a rainbow, tropical planting, and a pipe organ.",
        "sourceName": "Cinema Treasures",
        "sourceURL": "https://cinematreasures.org/theaters/838",
        "priority": 4,
        "onKalakaua": True,
        "onWaikikiBeach": False,
        "addressOrFrontage": "2284 Kalakaua Ave",
        "scopeDecision": "keep",
        "scopeNotes": "Historic building site directly on Kalakaua Avenue.",
    },
    {
        "id": "poi-outrigger-waikiki-beachcomber",
        "name": "OUTRIGGER Waikiki Beachcomber Hotel",
        "category": "landmark",
        "subcategory": "hotel_entertainment",
        "tags": ["kalakaua-avenue", "hotel", "entertainment"],
        "latitude": 21.278247,
        "longitude": -157.827342,
        "narration": "The Beachcomber layers local art, food, and live entertainment into a central Kalakaua hotel block.",
        "sourceName": "OUTRIGGER",
        "sourceURL": "https://www.outrigger.com/hawaii/oahu/outrigger-waikiki-beachcomber-hotel",
        "priority": 2,
        "onKalakaua": True,
        "onWaikikiBeach": False,
        "addressOrFrontage": "2300 Kalakaua Ave",
        "scopeDecision": "keep",
        "scopeNotes": "Official Kalakaua Avenue address.",
    },
    {
        "id": "poi-international-market-place",
        "name": "International Market Place",
        "category": "landmark",
        "subcategory": "retail_history",
        "tags": ["kalakaua-avenue", "retail", "banyan", "street-life"],
        "latitude": 21.277459,
        "longitude": -157.826838,
        "narration": "International Market Place began as a tiki-era open-air Waikiki marketplace and still centers its identity around a banyan-tree setting.",
        "sourceName": "International Market Place",
        "sourceURL": "https://shopinternationalmarketplace.com/",
        "sourceURLs": [
            "https://shopinternationalmarketplace.com/",
            "https://www.simon.com/mall/international-market-place",
        ],
        "priority": 4,
        "onKalakaua": True,
        "onWaikikiBeach": False,
        "addressOrFrontage": "2330 Kalakaua Ave",
        "scopeDecision": "keep",
        "scopeNotes": "Direct Kalakaua entrance.",
    },
    {
        "id": "poi-outrigger-waikiki-beach-resort",
        "name": "OUTRIGGER Waikiki Beach Resort",
        "category": "culture",
        "subcategory": "beachfront_hotel",
        "tags": ["kalakaua-avenue", "waikiki-beach", "beachboys", "music", "surf"],
        "latitude": 21.277005,
        "longitude": -157.827542,
        "narration": "Outrigger Waikiki Beach Resort ties Kalakaua's hotel strip directly to Duke's, live music, and Waikiki surf culture.",
        "sourceName": "OUTRIGGER",
        "sourceURL": "https://www.outrigger.com/hotels-resorts/hawaii/oahu/outrigger-waikiki-beach-resort",
        "priority": 4,
        "onKalakaua": True,
        "onWaikikiBeach": True,
        "addressOrFrontage": "2335 Kalakaua Ave",
        "scopeDecision": "keep",
        "scopeNotes": "Kalakaua address with direct Waikiki Beach frontage.",
    },
    {
        "id": "poi-apuakehau-stream-beachboys",
        "name": "Apuakehau Stream and Waikiki Beach Boys",
        "category": "culture",
        "subcategory": "surf_history",
        "tags": ["waikiki-beach", "beachboys", "surf", "historic-trail"],
        "latitude": 21.2767,
        "longitude": -157.8277,
        "narration": "Near the Outrigger and Moana beach edge, Apuakehau connects the old stream mouth with the Waikiki Beach Boys' surf legacy.",
        "sourceName": "Waikiki Historic Trail",
        "sourceURL": "https://www.waikikihistorictrail.org/apuakehau-stream-waikiki-beach-boys",
        "priority": 5,
        "onKalakaua": False,
        "onWaikikiBeach": True,
        "addressOrFrontage": "Waikiki Beach by Outrigger/Moana",
        "scopeDecision": "keep",
        "scopeNotes": "Historic Trail coordinates place it on the Waikiki Beach edge.",
    },
    {
        "id": "poi-moana-surfrider",
        "name": "Moana Surfrider",
        "category": "history",
        "subcategory": "historic_hotel",
        "tags": ["kalakaua-avenue", "waikiki-beach", "hotel", "architecture"],
        "latitude": 21.276499,
        "longitude": -157.826885,
        "narration": "Opened in 1901, the Moana Surfrider is Waikiki's original beachfront hotel and still puts its porte cochere on Kalakaua Avenue.",
        "sourceName": "Marriott",
        "sourceURL": "https://www.marriott.com/en-us/hotels/hnlwi-moana-surfrider-a-westin-resort-and-spa-waikiki-beach/rooms/wings-suites/history/",
        "sourceURLs": [
            "https://www.marriott.com/en-us/hotels/hnlwi-moana-surfrider-a-westin-resort-and-spa-waikiki-beach/rooms/wings-suites/history/",
            "https://historichawaii.org/article/history-and-architecture-in-waikiki/",
        ],
        "priority": 5,
        "onKalakaua": True,
        "onWaikikiBeach": True,
        "addressOrFrontage": "2365 Kalakaua Ave",
        "scopeDecision": "keep",
        "scopeNotes": "Historic Kalakaua hotel with Waikiki Beach frontage.",
    },
    {
        "id": "poi-moana-banyan-courtyard",
        "name": "Moana Banyan Courtyard",
        "category": "nature",
        "subcategory": "historic_tree",
        "tags": ["waikiki-beach", "banyan", "hotel", "history"],
        "latitude": 21.2769,
        "longitude": -157.8278,
        "narration": "The Moana courtyard banyan was planted in 1904 and now anchors one of Waikiki's oldest oceanfront hotel spaces.",
        "sourceName": "Marriott",
        "sourceURL": "https://www.marriott.com/en-us/hotels/hnlwi-moana-surfrider-a-westin-resort-and-spa-waikiki-beach/rooms/wings-suites/history/",
        "priority": 4,
        "onKalakaua": False,
        "onWaikikiBeach": True,
        "addressOrFrontage": "Inside Moana Surfrider beachfront courtyard",
        "scopeDecision": "keep",
        "scopeNotes": "On the Moana beachfront property.",
    },
    {
        "id": "poi-duke-kahanamoku-statue",
        "name": "Duke Kahanamoku Statue",
        "category": "culture",
        "subcategory": "public_art",
        "tags": ["kalakaua-avenue", "kuhio-beach", "surf", "statue"],
        "latitude": 21.275456,
        "longitude": -157.825304,
        "narration": "Duke Kahanamoku's bronze figure faces Kalakaua from Kuhio Beach, honoring the Waikiki waterman who carried surfing worldwide.",
        "sourceName": "Go Hawaii",
        "sourceURL": "https://www.gohawaii.com/islands/oahu/regions/honolulu/duke-kahanamoku-statue",
        "sourceURLs": [
            "https://www.gohawaii.com/islands/oahu/regions/honolulu/duke-kahanamoku-statue",
            "https://www.waikikihistorictrail.org/duke-kahanamoku",
        ],
        "priority": 5,
        "onKalakaua": True,
        "onWaikikiBeach": True,
        "addressOrFrontage": "Kuhio Beach at Uluniu Street",
        "scopeDecision": "keep",
        "scopeNotes": "On Kuhio Beach along Kalakaua Avenue.",
    },
    {
        "id": "poi-kuhio-beach-hula-mound",
        "name": "Kuhio Beach Hula Mound",
        "category": "culture",
        "subcategory": "performance_site",
        "tags": ["kalakaua-avenue", "kuhio-beach", "hula", "music"],
        "latitude": 21.2767,
        "longitude": -157.8259,
        "narration": "The Kuhio Beach Hula Mound keeps Hawaiian music and hula visible at the beach edge near the Duke statue.",
        "sourceName": "Waikiki Improvement Association",
        "sourceURL": "https://www.waikikiimprovement.com/events",
        "priority": 4,
        "onKalakaua": True,
        "onWaikikiBeach": True,
        "addressOrFrontage": "Beachside near Duke statue / Kalakaua",
        "scopeDecision": "keep",
        "scopeNotes": "WIA places the performance site beachside near the Duke statue.",
    },
    {
        "id": "poi-kapaemahu-stones",
        "name": "Na Pohaku Ola Kapaemahu a Kapuni",
        "category": "history",
        "subcategory": "cultural_site",
        "tags": ["waikiki-beach", "healing-stones", "culture", "kuhio-beach"],
        "latitude": 21.275773,
        "longitude": -157.825682,
        "narration": "The Kapaemahu stones preserve the story of four Tahitian healers whose healing power was remembered on Waikiki Beach.",
        "sourceName": "Waikiki Historic Trail",
        "sourceURL": "https://www.waikikihistorictrail.org/the-healing-stones-of-kapaemahu",
        "sourceURLs": [
            "https://www.waikikihistorictrail.org/the-healing-stones-of-kapaemahu",
            "https://kapaemahu.info/",
        ],
        "priority": 5,
        "onKalakaua": True,
        "onWaikikiBeach": True,
        "addressOrFrontage": "Kuhio Beach at Kaiulani Avenue",
        "scopeDecision": "keep",
        "scopeNotes": "Cultural site on Kuhio/Waikiki Beach immediately off Kalakaua.",
        "sensitivity": "cultural",
        "safetyFlags": ["avoid_sensationalizing"],
    },
    {
        "id": "poi-hyatt-regency-waikiki",
        "name": "Hyatt Regency Waikiki Beach Resort and Spa",
        "category": "landmark",
        "subcategory": "hotel",
        "tags": ["kalakaua-avenue", "hotel", "duke-statue"],
        "latitude": 21.276266,
        "longitude": -157.82545,
        "narration": "Hyatt Regency's twin towers sit across Kalakaua from the Duke statue in the dense center of the beach corridor.",
        "sourceName": "Hyatt",
        "sourceURL": "https://www.hyatt.com/hyatt-regency/en-US/hnlrw-hyatt-regency-waikiki-beach-resort-and-spa",
        "sourceURLs": [
            "https://www.hyatt.com/hyatt-regency/en-US/hnlrw-hyatt-regency-waikiki-beach-resort-and-spa",
            "https://files.hawaii.gov/dbedt/erp/EA_EIS_Library/2014-11-08-OA-DEA-2424-Kalakaua.pdf",
        ],
        "priority": 2,
        "onKalakaua": True,
        "onWaikikiBeach": False,
        "addressOrFrontage": "2424 Kalakaua Ave",
        "scopeDecision": "keep",
        "scopeNotes": "Official Kalakaua address across from Kuhio Beach.",
    },
    {
        "id": "poi-alohilani-resort-oceanarium",
        "name": "Alohilani Resort Oceanarium",
        "category": "landmark",
        "subcategory": "hotel_feature",
        "tags": ["kalakaua-avenue", "hotel", "oceanarium"],
        "latitude": 21.274667,
        "longitude": -157.82319,
        "narration": "Alohilani transformed the former Pacific Beach Hotel around a large lobby Oceanarium steps from Kuhio Beach.",
        "sourceName": "Alohilani Resort",
        "sourceURL": "https://www.alohilaniresort.com/transformation/",
        "priority": 3,
        "onKalakaua": True,
        "onWaikikiBeach": False,
        "addressOrFrontage": "2490 Kalakaua Ave",
        "scopeDecision": "keep",
        "scopeNotes": "Official Kalakaua address near Kuhio Beach.",
    },
    {
        "id": "poi-prince-kuhio-statue",
        "name": "Prince Jonah Kuhio Kalanianaole Statue",
        "category": "culture",
        "subcategory": "public_art",
        "tags": ["kalakaua-avenue", "kuhio-beach", "statue", "public-art"],
        "latitude": 21.273389,
        "longitude": -157.823802,
        "narration": "Prince Kuhio's bronze figure anchors the civic-art stretch of Kuhio Beach Park on Kalakaua.",
        "sourceName": "City and County of Honolulu Public Art",
        "sourceURL": "https://data.honolulu.gov/api/views/yef5-h88r/rows.pdf?accessType=DOWNLOAD",
        "priority": 4,
        "onKalakaua": True,
        "onWaikikiBeach": True,
        "addressOrFrontage": "Kuhio Beach / 2501-2537 Kalakaua Ave",
        "scopeDecision": "keep",
        "scopeNotes": "City public-art data places the statue on Kuhio Beach along Kalakaua.",
    },
    {
        "id": "poi-prince-kuhio-historic-marker",
        "name": "Prince Kuhio Historic Trail Marker",
        "category": "history",
        "subcategory": "historic_marker",
        "tags": ["kalakaua-avenue", "kuhio-beach", "historic-trail", "royal-history"],
        "latitude": 21.273181,
        "longitude": -157.823751,
        "narration": "The Prince Kuhio marker ties royal lineage, public service, and Hawaiian Homes advocacy to this beach park.",
        "sourceName": "Waikiki Historic Trail",
        "sourceURL": "https://www.waikikihistorictrail.org/prince-jonah-khi-kalanianaole-piikoi",
        "priority": 4,
        "onKalakaua": True,
        "onWaikikiBeach": True,
        "addressOrFrontage": "Kuhio Beach near Ohua Street",
        "scopeDecision": "keep",
        "scopeNotes": "Historic marker on the Kalakaua beach edge.",
    },
    {
        "id": "poi-kuhio-beach-park",
        "name": "Kuhio Beach Park",
        "category": "nature",
        "subcategory": "beach_park",
        "tags": ["kalakaua-avenue", "waikiki-beach", "kuhio-beach", "protected-water"],
        "latitude": 21.2750,
        "longitude": -157.8269,
        "narration": "Kuhio Beach Park is central Waikiki's beach section, shaped by seawalls, groins, public art, and protected swimming water.",
        "sourceName": "To-Hawaii",
        "sourceURL": "https://www.to-hawaii.com/oahu/beaches/kuhiobeach.php",
        "sourceURLs": [
            "https://www.to-hawaii.com/oahu/beaches/kuhiobeach.php",
            "https://dlnr.hawaii.gov/dobor/where-can-i-fish/",
        ],
        "priority": 4,
        "onKalakaua": True,
        "onWaikikiBeach": True,
        "addressOrFrontage": "Waikiki Beach from Moana/Kuhio toward Kapahulu",
        "scopeDecision": "keep",
        "scopeNotes": "Part of Waikiki Beach directly along Kalakaua.",
    },
    {
        "id": "poi-kuhio-beach-swimming-zone",
        "name": "Kuhio Beach Swimming Zone",
        "category": "nature",
        "subcategory": "shoreline_engineering",
        "tags": ["waikiki-beach", "kuhio-beach", "groin", "swimming"],
        "latitude": 21.2750,
        "longitude": -157.8269,
        "narration": "Kuhio's protected swimming area is bounded by groins, seawall, and shoreline, making this stretch feel calmer than open reef water.",
        "sourceName": "Hawaii DLNR DOBOR",
        "sourceURL": "https://dlnr.hawaii.gov/dobor/where-can-i-fish/",
        "priority": 4,
        "onKalakaua": False,
        "onWaikikiBeach": True,
        "addressOrFrontage": "Kuhio Beach protected swimming area",
        "scopeDecision": "keep",
        "scopeNotes": "DLNR describes the exact Kuhio Beach swimming-area boundaries.",
    },
    {
        "id": "poi-waikiki-beach-marker",
        "name": "Waikiki Historic Trail Beach Marker",
        "category": "history",
        "subcategory": "historic_marker",
        "tags": ["kalakaua-avenue", "waikiki-beach", "historic-trail", "surf"],
        "latitude": 21.271572,
        "longitude": -157.822882,
        "narration": "The Waikiki marker explains the area's older identity as a watery chiefly surf place with named breaks and long rides.",
        "sourceName": "Waikiki Historic Trail",
        "sourceURL": "https://www.waikikihistorictrail.org/waikki",
        "priority": 4,
        "onKalakaua": True,
        "onWaikikiBeach": True,
        "addressOrFrontage": "Kuhio Beach at Kapahulu Avenue",
        "scopeDecision": "keep",
        "scopeNotes": "Historic marker at the Kalakaua/Kapahulu beach end.",
    },
    {
        "id": "poi-makua-and-kila",
        "name": "Makua and Kila",
        "category": "culture",
        "subcategory": "public_art",
        "tags": ["kalakaua-avenue", "kuhio-beach", "public-art", "monk-seal", "surf"],
        "latitude": 21.271524,
        "longitude": -157.822906,
        "narration": "Makua and Kila pairs a boy on a surfboard with a monk seal, giving the Kapahulu end a playful surf-and-sea-life marker.",
        "sourceName": "City and County of Honolulu Public Art",
        "sourceURL": "https://data.honolulu.gov/api/views/yef5-h88r/rows.pdf?accessType=DOWNLOAD",
        "priority": 3,
        "onKalakaua": True,
        "onWaikikiBeach": True,
        "addressOrFrontage": "Kuhio Beach at Kapahulu Avenue",
        "scopeDecision": "keep",
        "scopeNotes": "City public-art data places the sculpture at Kuhio Beach/Kapahulu.",
    },
    {
        "id": "poi-surfer-on-a-wave",
        "name": "Surfer on a Wave",
        "category": "culture",
        "subcategory": "public_art",
        "tags": ["kalakaua-avenue", "kuhio-beach", "public-art", "surf"],
        "latitude": 21.270492,
        "longitude": -157.822447,
        "narration": "Surfer on a Wave turns Waikiki's surf identity into a life-size sculpture visible from the beach sidewalk.",
        "sourceName": "City and County of Honolulu Public Art",
        "sourceURL": "https://data.honolulu.gov/api/views/yef5-h88r/rows.pdf?accessType=DOWNLOAD",
        "priority": 3,
        "onKalakaua": True,
        "onWaikikiBeach": True,
        "addressOrFrontage": "Kuhio Beach near Monsarrat Avenue",
        "scopeDecision": "keep",
        "scopeNotes": "City public-art data places the sculpture on Kuhio Beach frontage.",
    },
    {
        "id": "poi-kapahulu-groin-walls",
        "name": "Kapahulu Groin / The Wall",
        "category": "landmark",
        "subcategory": "shoreline_feature",
        "tags": ["waikiki-beach", "kuhio-beach", "groin", "surf", "bodyboarding"],
        "latitude": 21.2729,
        "longitude": -157.8228,
        "narration": "The Kapahulu Groin separates Kuhio Beach from the Kapiolani side and helps define the Wall bodyboarding zone.",
        "sourceName": "To-Hawaii",
        "sourceURL": "https://www.to-hawaii.com/oahu/beaches/kuhiobeach.php",
        "priority": 4,
        "onKalakaua": True,
        "onWaikikiBeach": True,
        "addressOrFrontage": "Kalakaua/Kapahulu beach edge",
        "scopeDecision": "keep",
        "scopeNotes": "Visible shoreline feature at the route end.",
    },
    {
        "id": "poi-waikiki-beach-nourishment",
        "name": "Central Waikiki Beach Nourishment",
        "category": "nature",
        "subcategory": "shoreline_engineering",
        "tags": ["waikiki-beach", "shoreline", "sand", "engineering"],
        "latitude": 21.277333,
        "longitude": -157.828968,
        "narration": "A 2012 beach project restored a central Waikiki stretch with offshore sand, widening the beach between the Kuhio wall and Royal Hawaiian groin.",
        "sourceName": "Hawaii DLNR OCCL",
        "sourceURL": "https://dlnr.hawaii.gov/occl/files/2013/08/2012-Waikiki-Beach-Maintenance-Final-Report.pdf",
        "priority": 4,
        "onKalakaua": False,
        "onWaikikiBeach": True,
        "addressOrFrontage": "Central Waikiki Beach / Royal Hawaiian groin",
        "scopeDecision": "keep",
        "scopeNotes": "Directly about the engineered shoreline visible from Waikiki Beach.",
    },
    {
        "id": "poi-canoes-surf-break",
        "name": "Canoes Surf Break",
        "category": "culture",
        "subcategory": "surf_break",
        "tags": ["waikiki-beach", "surf", "canoes", "royal-hawaiian"],
        "latitude": 21.277333,
        "longitude": -157.828968,
        "narration": "Canoes is the classic beginner-friendly Waikiki wave offshore of the Royal Hawaiian beach frontage.",
        "sourceName": "Hawaiian South Shore",
        "sourceURL": "https://www.hawaiiansouthshore.com/blogs/waves-of-the-south-shore-series/surf-guide-series-canoes-hawaii",
        "priority": 4,
        "onKalakaua": False,
        "onWaikikiBeach": True,
        "addressOrFrontage": "Offshore from central Waikiki/Royal Hawaiian",
        "scopeDecision": "keep",
        "scopeNotes": "Named surf break directly off Waikiki Beach.",
    },
    {
        "id": "poi-queens-surf-break",
        "name": "Queen's Surf Break",
        "category": "culture",
        "subcategory": "surf_break",
        "tags": ["waikiki-beach", "surf", "queens", "reef"],
        "latitude": 21.2720,
        "longitude": -157.8240,
        "narration": "Queen's is an eastern Waikiki reef break tied to the Kuhio and Kapiolani Park edge of the beach.",
        "sourceName": "Hawaii Surf",
        "sourceURL": "https://hawaii.surf/queens-surf-break-waikiki-guide/",
        "priority": 4,
        "onKalakaua": False,
        "onWaikikiBeach": True,
        "addressOrFrontage": "Off Queen's/Kuhio Beach",
        "scopeDecision": "keep",
        "scopeNotes": "Named surf break on the Waikiki Beach edge.",
    },
    {
        "id": "poi-publics-reef-break",
        "name": "Publics Reef Break",
        "category": "culture",
        "subcategory": "surf_break",
        "tags": ["waikiki-beach", "surf", "reef", "aquarium"],
        "latitude": 21.265673,
        "longitude": -157.821724,
        "narration": "Publics is a left-hand reef break off the Aquarium end of Waikiki's beach-and-reef corridor.",
        "sourceName": "Hawaiian South Shore",
        "sourceURL": "https://www.hawaiiansouthshore.com/blogs/waves-of-the-south-shore-series/surf-guide-series-publics-hawaii",
        "priority": 3,
        "onKalakaua": False,
        "onWaikikiBeach": True,
        "addressOrFrontage": "Off Waikiki Aquarium / Queen's Beach edge",
        "scopeDecision": "keep",
        "scopeNotes": "Beach-edge surf/reef fact at the Diamond Head end.",
    },
    {
        "id": "poi-waikiki-mlcd-boundary",
        "name": "Waikiki Marine Life Conservation District",
        "category": "nature",
        "subcategory": "marine_conservation",
        "tags": ["waikiki-beach", "reef", "marine-life", "conservation"],
        "latitude": 21.2657,
        "longitude": -157.8217,
        "narration": "At Waikiki's Diamond Head end, the Marine Life Conservation District protects reef habitat extending offshore from the Kapahulu groin toward the Natatorium.",
        "sourceName": "Hawaii DLNR DAR",
        "sourceURL": "https://dlnr.hawaii.gov/dar/marine-managed-areas/hawaii-marine-life-conservation-districts/oahu-waikiki/",
        "priority": 4,
        "onKalakaua": False,
        "onWaikikiBeach": True,
        "addressOrFrontage": "Diamond Head end of Waikiki Beach",
        "scopeDecision": "keep",
        "scopeNotes": "Beach-visible marine conservation zone.",
    },
    {
        "id": "poi-waikiki-aquarium-reef-flat",
        "name": "Waikiki Aquarium Reef Flat",
        "category": "nature",
        "subcategory": "reef",
        "tags": ["waikiki-beach", "reef", "aquarium", "marine-life"],
        "latitude": 21.265673,
        "longitude": -157.821724,
        "narration": "Just off the Aquarium seawall, a shallow reef flat and dredged channel concentrate fish along the Diamond Head end of Waikiki.",
        "sourceName": "Hawaii DLNR DAR",
        "sourceURL": "https://dlnr.hawaii.gov/dar/marine-managed-areas/hawaii-marine-life-conservation-districts/oahu-waikiki/",
        "priority": 3,
        "onKalakaua": False,
        "onWaikikiBeach": True,
        "addressOrFrontage": "Waikiki Aquarium seawall / reef edge",
        "scopeDecision": "keep",
        "scopeNotes": "Direct reef fact for the Waikiki Beach edge.",
    },
    {
        "id": "poi-waikiki-beach-marriott",
        "name": "Waikiki Beach Marriott Resort and Spa",
        "category": "history",
        "subcategory": "hotel_site",
        "tags": ["kalakaua-avenue", "hotel", "queen-liliuokalani"],
        "latitude": 21.273206,
        "longitude": -157.822375,
        "narration": "Waikiki Beach Marriott stands on a Kalakaua site associated with Queen Liliuokalani's former Waikiki residences.",
        "sourceName": "Marriott",
        "sourceURL": "https://www.marriott.com/en-us/hotels/hnlmc-waikiki-beach-marriott-resort-and-spa/overview/",
        "priority": 3,
        "onKalakaua": True,
        "onWaikikiBeach": False,
        "addressOrFrontage": "2552 Kalakaua Ave",
        "scopeDecision": "keep",
        "scopeNotes": "Official Kalakaua address near the Kapahulu end.",
    },
    {
        "id": "poi-twin-fin-hotel",
        "name": "The Twin Fin Hotel",
        "category": "landmark",
        "subcategory": "surf_hotel",
        "tags": ["kalakaua-avenue", "hotel", "surf", "kuhio-beach"],
        "latitude": 21.2728,
        "longitude": -157.8222,
        "narration": "The Twin Fin leans into Waikiki surf culture from the Diamond Head end of Kalakaua near Kuhio Beach.",
        "sourceName": "The Twin Fin",
        "sourceURL": "https://www.twinfinwaikiki.com/about/",
        "priority": 2,
        "onKalakaua": True,
        "onWaikikiBeach": False,
        "addressOrFrontage": "2570 Kalakaua Ave",
        "scopeDecision": "keep",
        "scopeNotes": "Official Kalakaua address near the route end.",
    },
    {
        "id": "poi-sans-souci-beach",
        "name": "Sans Souci / Kaimana Beach",
        "category": "nature",
        "subcategory": "beach",
        "tags": ["waikiki-beach", "kaimana", "sans-souci", "swimming"],
        "latitude": 21.2649,
        "longitude": -157.8204,
        "narration": "Sans Souci, also known as Kaimana Beach, is the quieter Diamond Head end of Waikiki's beach corridor.",
        "sourceName": "To-Hawaii",
        "sourceURL": "https://www.to-hawaii.com/oahu/beaches/sanssoucibeach.php",
        "priority": 2,
        "onKalakaua": False,
        "onWaikikiBeach": True,
        "addressOrFrontage": "Diamond Head end of Waikiki Beach",
        "scopeDecision": "keep_edge",
        "scopeNotes": "Strict beach-corridor item; not on the Kalakaua driving route.",
    },
    {
        "id": "poi-dukes-waikiki",
        "name": "Duke's Waikiki",
        "category": "food",
        "subcategory": "beachfront_restaurant",
        "tags": ["kalakaua-avenue", "waikiki-beach", "food", "duke-kahanamoku", "live-music"],
        "latitude": 21.2769,
        "longitude": -157.8275,
        "narration": "Duke's Waikiki puts food, live music, and Duke Kahanamoku memorabilia directly on the Outrigger's beachfront edge.",
        "sourceName": "Duke's Waikiki",
        "sourceURL": "https://www.dukeswaikiki.com/",
        "priority": 4,
        "onKalakaua": True,
        "onWaikikiBeach": True,
        "addressOrFrontage": "2335 Kalakaua Ave",
        "scopeDecision": "keep",
        "scopeNotes": "Beachfront restaurant inside Outrigger Waikiki Beach Resort.",
    },
    {
        "id": "poi-hula-grill-waikiki",
        "name": "Hula Grill Waikiki",
        "category": "food",
        "subcategory": "beachfront_restaurant",
        "tags": ["kalakaua-avenue", "waikiki-beach", "food", "local-ingredients"],
        "latitude": 21.2769,
        "longitude": -157.8275,
        "narration": "Hula Grill sits above the Outrigger beach walk, framing local-style food with a direct Waikiki Beach view.",
        "sourceName": "Hula Grill Waikiki",
        "sourceURL": "https://www.hulagrillwaikiki.com/",
        "priority": 3,
        "onKalakaua": True,
        "onWaikikiBeach": True,
        "addressOrFrontage": "2335 Kalakaua Ave",
        "scopeDecision": "keep",
        "scopeNotes": "Beachfront dining at the Outrigger Waikiki Beach Resort address.",
    },
    {
        "id": "poi-monkeypod-waikiki",
        "name": "Monkeypod Kitchen Waikiki",
        "category": "food",
        "subcategory": "restaurant",
        "tags": ["kalakaua-avenue", "food", "royal-hawaiian-center", "hawaii-regional"],
        "latitude": 21.27948,
        "longitude": -157.830062,
        "narration": "Monkeypod brings a Hawaii regional menu into Royal Hawaiian Center, giving the Kalakaua retail core a food stop with local sourcing cues.",
        "sourceName": "Monkeypod Kitchen",
        "sourceURL": "https://monkeypodkitchen.com/locations/waikiki/",
        "priority": 3,
        "onKalakaua": True,
        "onWaikikiBeach": False,
        "addressOrFrontage": "2201 Kalakaua Ave, Royal Hawaiian Center",
        "scopeDecision": "keep",
        "scopeNotes": "Located in Royal Hawaiian Center on Kalakaua Avenue.",
    },
    {
        "id": "poi-restaurant-suntory",
        "name": "Restaurant Suntory",
        "category": "food",
        "subcategory": "japanese_restaurant",
        "tags": ["kalakaua-avenue", "food", "royal-hawaiian-center", "japanese"],
        "latitude": 21.27948,
        "longitude": -157.830062,
        "narration": "Restaurant Suntory adds a long-running Japanese dining layer to Royal Hawaiian Center's Kalakaua food scene.",
        "sourceName": "Restaurant Suntory",
        "sourceURL": "https://restaurantsuntory.com/",
        "priority": 2,
        "onKalakaua": True,
        "onWaikikiBeach": False,
        "addressOrFrontage": "2233 Kalakaua Ave / Royal Hawaiian Center",
        "scopeDecision": "keep",
        "scopeNotes": "Official site lists a Kalakaua Avenue Waikiki address.",
    },
    {
        "id": "poi-doraku-sushi-waikiki",
        "name": "Doraku Sushi Waikiki",
        "category": "food",
        "subcategory": "sushi",
        "tags": ["kalakaua-avenue", "food", "royal-hawaiian-center", "japanese"],
        "latitude": 21.27948,
        "longitude": -157.830062,
        "narration": "Doraku Sushi sits above the Kalakaua and Seaside corner inside Royal Hawaiian Center.",
        "sourceName": "Doraku Sushi",
        "sourceURL": "https://dorakusushi.com/waikiki/",
        "priority": 2,
        "onKalakaua": True,
        "onWaikikiBeach": False,
        "addressOrFrontage": "Royal Hawaiian Center, Kalakaua/Seaside",
        "scopeDecision": "keep",
        "scopeNotes": "Source places it in Royal Hawaiian Center with escalator access at Kalakaua and Seaside.",
    },
    {
        "id": "poi-stripsteak-waikiki",
        "name": "STRIPSTEAK Waikiki",
        "category": "food",
        "subcategory": "restaurant",
        "tags": ["kalakaua-avenue", "food", "international-market-place"],
        "latitude": 21.277459,
        "longitude": -157.826838,
        "narration": "STRIPSTEAK brings a Michael Mina steakhouse layer to International Market Place's Grand Lanai above Kalakaua.",
        "sourceName": "Mina Group",
        "sourceURL": "https://theminagroup.com/restaurants/stripsteak-waikiki/",
        "priority": 2,
        "onKalakaua": True,
        "onWaikikiBeach": False,
        "addressOrFrontage": "2330 Kalakaua Ave, International Market Place",
        "scopeDecision": "keep",
        "scopeNotes": "Official site lists International Market Place / Kalakaua Avenue.",
    },
    {
        "id": "poi-lulus-waikiki",
        "name": "Lulu's Waikiki",
        "category": "food",
        "subcategory": "beach_view_restaurant",
        "tags": ["kalakaua-avenue", "food", "kuhio-beach", "beach-view"],
        "latitude": 21.2724,
        "longitude": -157.8221,
        "narration": "Lulu's sits across from Kuhio Beach at the Diamond Head end of Kalakaua, with an open-air view over the beach edge.",
        "sourceName": "Lulu's Waikiki",
        "sourceURL": "https://www.luluswaikiki.com/",
        "priority": 3,
        "onKalakaua": True,
        "onWaikikiBeach": False,
        "addressOrFrontage": "2586 Kalakaua Ave",
        "scopeDecision": "keep",
        "scopeNotes": "Official address is on Kalakaua across from Waikiki/Kuhio Beach.",
    },
    {
        "id": "poi-big-island-burger-waikiki",
        "name": "Big Island Burger Waikiki",
        "category": "food",
        "subcategory": "casual_food",
        "tags": ["kalakaua-avenue", "food", "burger", "waikiki-shopping-plaza"],
        "latitude": 21.2793,
        "longitude": -157.8285,
        "narration": "Big Island Burger adds a casual local-beef food stop to Waikiki Shopping Plaza on Kalakaua.",
        "sourceName": "Big Island Burger",
        "sourceURL": "https://bigislandburger.net/",
        "priority": 2,
        "onKalakaua": True,
        "onWaikikiBeach": False,
        "addressOrFrontage": "2250 Kalakaua Ave",
        "scopeDecision": "keep",
        "scopeNotes": "Official site lists the Waikiki Shopping Plaza / Kalakaua address.",
    },
    {
        "id": "event-kuhio-beach-hula-show",
        "name": "Kuhio Beach Hula Show",
        "category": "event",
        "subcategory": "recurring_cultural_performance",
        "tags": ["kalakaua-avenue", "kuhio-beach", "hula", "music", "recurring-event"],
        "latitude": 21.2767,
        "longitude": -157.8259,
        "narration": "The Kuhio Beach Hula Show brings free Hawaiian music and hula to the beachside mound on Tuesday and Saturday evenings.",
        "sourceName": "Kuhio Beach Hula Show",
        "sourceURL": "https://kbhulashow.wixsite.com/official?_escaped_fragment_=schedule%2Fc21r&lightbox=image1g4t",
        "priority": 5,
        "onKalakaua": True,
        "onWaikikiBeach": True,
        "addressOrFrontage": "Kuhio Beach Hula Mound",
        "scopeDecision": "keep_event",
        "scopeNotes": "Recurring event at the beachside hula mound along Kalakaua.",
        "evergreen": False,
        "freshness": "recurring_schedule",
        "recurrence": "Tuesdays and Saturdays, weather permitting",
    },
    {
        "id": "event-pan-pacific-festival-2026",
        "name": "Pan-Pacific Festival 2026",
        "category": "event",
        "subcategory": "upcoming_festival",
        "tags": ["kalakaua-avenue", "festival", "parade", "street-party", "upcoming-event"],
        "latitude": 21.2785,
        "longitude": -157.8279,
        "narration": "The Pan-Pacific Festival returns June 12-14, 2026, with Kalakaua Avenue as the main parade and street-festival spine.",
        "sourceName": "Pan-Pacific Festival",
        "sourceURL": "https://www.panpacificfestival.org/event/pan-pacific-parade/",
        "priority": 5,
        "onKalakaua": True,
        "onWaikikiBeach": False,
        "addressOrFrontage": "Kalakaua Avenue",
        "scopeDecision": "keep_event",
        "scopeNotes": "Official festival page places the parade along Kalakaua Avenue.",
        "evergreen": False,
        "freshness": "dated_2026",
        "eventStartDate": "2026-06-12",
        "eventEndDate": "2026-06-14",
    },
    {
        "id": "event-king-kamehameha-floral-parade-2026",
        "name": "King Kamehameha Celebration Floral Parade 2026",
        "category": "event",
        "subcategory": "upcoming_parade",
        "tags": ["kalakaua-avenue", "parade", "king-kamehameha", "upcoming-event"],
        "latitude": 21.2785,
        "longitude": -157.8279,
        "narration": "On June 13, 2026, the King Kamehameha Floral Parade is scheduled to continue onto Kalakaua Avenue before ending near Monsarrat.",
        "sourceName": "Culture and Arts on Oahu",
        "sourceURL": "https://www.thecreativecity.org/events/acpjyd5x49ztlpl-8adf4-ppjm6-8k72k-wgc62-cd5zh-rzj4f-74gzb-29ykd-4t5cm-63843-y84dj-hnas6-zjwwm-b3ekn-j3gg4-9f9lt-ljlbm-hn22x",
        "priority": 4,
        "onKalakaua": True,
        "onWaikikiBeach": False,
        "addressOrFrontage": "Kalakaua Avenue parade route",
        "scopeDecision": "keep_event",
        "scopeNotes": "Current event listing names Kalakaua Avenue in the parade route.",
        "evergreen": False,
        "freshness": "dated_2026",
        "eventStartDate": "2026-06-13",
        "eventEndDate": "2026-06-13",
    },
    {
        "id": "event-aloha-festivals-floral-parade-2026",
        "name": "Aloha Festivals Floral Parade 2026",
        "category": "event",
        "subcategory": "upcoming_parade",
        "tags": ["kalakaua-avenue", "parade", "aloha-festivals", "upcoming-event"],
        "latitude": 21.2785,
        "longitude": -157.8279,
        "narration": "The 2026 Aloha Festivals Floral Parade is scheduled to travel from Ala Moana Park along Kalakaua Avenue to Kapiolani Park.",
        "sourceName": "Aloha Festivals",
        "sourceURL": "https://www.alohafestivals.com/floral-parade/",
        "priority": 4,
        "onKalakaua": True,
        "onWaikikiBeach": False,
        "addressOrFrontage": "Kalakaua Avenue parade route",
        "scopeDecision": "keep_event",
        "scopeNotes": "Official event page lists Kalakaua Avenue as the parade route.",
        "evergreen": False,
        "freshness": "dated_2026",
        "eventStartDate": "2026-09-26",
        "eventEndDate": "2026-09-26",
    },
    {
        "id": "event-royal-hawaiian-center-cultural-programming",
        "name": "Royal Hawaiian Center Cultural Programming",
        "category": "event",
        "subcategory": "recurring_cultural_activity",
        "tags": ["kalakaua-avenue", "hula", "lei", "ukulele", "recurring-event"],
        "latitude": 21.27948,
        "longitude": -157.830062,
        "narration": "Royal Hawaiian Center regularly stages cultural activities such as hula, music, ukulele, lei-making, and keiki programs in the Kalakaua retail core.",
        "sourceName": "Royal Hawaiian Center",
        "sourceURL": "https://www.royalhawaiiancenter.com/events",
        "priority": 3,
        "onKalakaua": True,
        "onWaikikiBeach": False,
        "addressOrFrontage": "2201 Kalakaua Ave",
        "scopeDecision": "keep_event",
        "scopeNotes": "Official events page for a Kalakaua Avenue center.",
        "evergreen": False,
        "freshness": "recurring_schedule",
        "recurrence": "Recurring cultural activities; verify day/time before narration",
    },
    {
        "id": "event-royal-hawaiian-ahaaina-luau",
        "name": "Ahaaina Luau at The Royal Hawaiian",
        "category": "event",
        "subcategory": "recurring_luau",
        "tags": ["kalakaua-avenue", "waikiki-beach", "luau", "hula", "food"],
        "latitude": 21.277333,
        "longitude": -157.828968,
        "narration": "The Royal Hawaiian's Ahaaina luau pairs food, hula, music, and storytelling on the Pink Palace's Waikiki Beach frontage.",
        "sourceName": "The Royal Hawaiian",
        "sourceURL": "https://www.royal-hawaiian.com/dining-overview/ahaaina-luau/",
        "priority": 3,
        "onKalakaua": True,
        "onWaikikiBeach": True,
        "addressOrFrontage": "2259 Kalakaua Ave",
        "scopeDecision": "keep_event",
        "scopeNotes": "Recurring event at a Kalakaua hotel with beach frontage.",
        "evergreen": False,
        "freshness": "recurring_schedule",
        "recurrence": "Mondays and Thursdays per source; verify before live use",
    },
    {
        "id": "event-waikiki-friday-fireworks",
        "name": "Waikiki Friday Fireworks",
        "category": "event",
        "subcategory": "recurring_fireworks",
        "tags": ["waikiki-beach", "fireworks", "friday", "recurring-event"],
        "latitude": 21.2836,
        "longitude": -157.8355,
        "narration": "Friday night fireworks launch from the Hilton Hawaiian Village beachfront and are often visible along western Waikiki Beach.",
        "sourceName": "Hilton Hawaiian Village",
        "sourceURL": "https://hiltonhawaiianvillage.com/events/friday-night-fireworks/",
        "priority": 3,
        "onKalakaua": False,
        "onWaikikiBeach": True,
        "addressOrFrontage": "Duke Kahanamoku Beach / western Waikiki Beach",
        "scopeDecision": "keep_edge_event",
        "scopeNotes": "Beach-visible recurring event at the western Waikiki shoreline; not on the Kalakaua driving route.",
        "evergreen": False,
        "freshness": "recurring_schedule",
        "recurrence": "Friday evenings; verify time before narration",
    },
]

OFFICIAL_SOURCE_HINTS = (
    "honolulu.gov",
    "hawaii.gov",
    "dlnr.hawaii.gov",
    "gohawaii.com",
    "bishopmuseum.org",
    "iolani",
    "waikikiaquarium.org",
)

CATEGORY_TAGS = {
    "area": ["neighborhood", "local-life"],
    "culture": ["culture", "hawaii"],
    "food": ["food", "local-business"],
    "history": ["history", "heritage"],
    "landmark": ["landmark", "architecture"],
    "lookout": ["viewpoint", "nature"],
    "nature": ["nature", "park"],
    "event": ["event", "time-sensitive"],
}


def canonical_id(name: str, category: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")
    prefix = "area" if category == "area" else "poi"
    return f"{prefix}-{slug}"


def confidence_for(source_url: str, source_name: str) -> float:
    source_text = f"{source_name} {source_url}".lower()
    if any(hint in source_text for hint in OFFICIAL_SOURCE_HINTS):
        return 0.95
    if "wikipedia.org" in source_text:
        return 0.78
    return 0.84


def normalize_fact(raw: dict) -> dict:
    category = raw["category"].lower()
    priority = int(raw["priority"])
    source_url = raw["sourceURL"]
    tags = sorted(set(raw.get("tags", []) + CATEGORY_TAGS.get(category, [])))
    importance = min(1.0, max(0.0, priority / 5))
    visual_categories = {"landmark", "lookout", "nature", "area"}
    drive_by_categories = {"area", "landmark", "lookout", "history", "culture"}

    fact = {
        **raw,
        "id": raw.get("id") or canonical_id(raw["name"], category),
        "category": category,
        "subcategory": raw.get("subcategory") or category,
        "tags": tags,
        "sourceURLs": sorted(set(raw.get("sourceURLs", [source_url]))),
        "sourceConfidence": raw.get("sourceConfidence", confidence_for(source_url, raw["sourceName"])),
        "culturalImportance": raw.get("culturalImportance", importance if category == "culture" else min(0.85, importance * 0.7)),
        "historicImportance": raw.get("historicImportance", importance if category == "history" else min(0.85, importance * 0.65)),
        "visualProminence": raw.get("visualProminence", min(1.0, 0.35 + (0.12 * priority)) if category in visual_categories else 0.35),
        "driveByValue": raw.get("driveByValue", min(1.0, 0.40 + (0.12 * priority)) if category in drive_by_categories else 0.45),
        "sensitivity": raw.get("sensitivity", "normal"),
        "safetyFlags": raw.get("safetyFlags", []),
        "evergreen": raw.get("evergreen", True),
        "freshness": raw.get("freshness", "evergreen"),
        "eventStartDate": raw.get("eventStartDate"),
        "eventEndDate": raw.get("eventEndDate"),
        "recurrence": raw.get("recurrence"),
    }
    fact["sourceConfidence"] = round(float(fact["sourceConfidence"]), 2)
    fact["culturalImportance"] = round(float(fact["culturalImportance"]), 2)
    fact["historicImportance"] = round(float(fact["historicImportance"]), 2)
    fact["visualProminence"] = round(float(fact["visualProminence"]), 2)
    fact["driveByValue"] = round(float(fact["driveByValue"]), 2)
    return fact


def dedupe_facts(facts: list[dict]) -> list[dict]:
    seen: set[tuple[str, int, int]] = set()
    result: list[dict] = []
    for fact in facts:
        key = (
            re.sub(r"[^a-z0-9]+", "", fact["name"].lower()),
            round(float(fact["latitude"]) * 10_000),
            round(float(fact["longitude"]) * 10_000),
        )
        if key in seen:
            continue
        seen.add(key)
        result.append(fact)
    return result


REVIEW_FIELDS = [
    "id",
    "name",
    "category",
    "subcategory",
    "latitude",
    "longitude",
    "addressOrFrontage",
    "onKalakaua",
    "onWaikikiBeach",
    "scopeDecision",
    "scopeNotes",
    "tags",
    "priority",
    "sourceConfidence",
    "culturalImportance",
    "historicImportance",
    "visualProminence",
    "driveByValue",
    "sensitivity",
    "safetyFlags",
    "evergreen",
    "freshness",
    "eventStartDate",
    "eventEndDate",
    "recurrence",
    "sourceName",
    "sourceURL",
    "narration",
]


def write_review_csv(facts: list[dict], path: Path) -> None:
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=REVIEW_FIELDS)
        writer.writeheader()
        for fact in facts:
            row = {field: fact.get(field, "") for field in REVIEW_FIELDS}
            row["tags"] = ", ".join(fact.get("tags", []))
            row["safetyFlags"] = ", ".join(fact.get("safetyFlags", []))
            writer.writerow(row)


ROUTE = [
    ("kalakaua-001", "Kalakaua Avenue at Ala Moana Boulevard", 21.285546, -157.832941, 0.0),
    ("kalakaua-002", "Kalakaua Avenue at Ala Moana Boulevard", 21.284828, -157.832516, 13.6),
    ("kalakaua-003", "Kalakaua Avenue at Ala Moana Boulevard", 21.284613, -157.832371, 17.8),
    ("kalakaua-004", "Kalakaua Avenue at Ala Moana Boulevard", 21.284247, -157.832118, 25.0),
    ("kalakaua-005", "Kalakaua Avenue at Ala Moana Boulevard", 21.284028, -157.831980, 29.3),
    ("kalakaua-006", "Kalakaua Avenue at Ala Moana Boulevard", 21.283881, -157.831896, 32.0),
    ("kalakaua-007", "Kalakaua Avenue at Ala Moana Boulevard", 21.283747, -157.831820, 34.5),
    ("kalakaua-008", "Kalakaua Avenue at Ala Moana Boulevard", 21.283654, -157.831767, 36.3),
    ("kalakaua-009", "Kalakaua Avenue at Ala Moana Boulevard", 21.283304, -157.831569, 42.9),
    ("kalakaua-010", "Waikiki Gateway", 21.283051, -157.831425, 47.6),
    ("kalakaua-011", "Waikiki Gateway", 21.282907, -157.831343, 50.3),
    ("kalakaua-012", "Waikiki Gateway", 21.282423, -157.831089, 59.3),
    ("kalakaua-013", "Waikiki Gateway", 21.282324, -157.831038, 61.1),
    ("kalakaua-014", "Waikiki Gateway", 21.281903, -157.830814, 68.9),
    ("kalakaua-015", "Waikiki Gateway", 21.281876, -157.830800, 69.4),
    ("kalakaua-016", "Waikiki Gateway", 21.281491, -157.830590, 76.5),
    ("kalakaua-017", "Waikiki Gateway", 21.281288, -157.830474, 80.4),
    ("kalakaua-018", "Fort DeRussy Beach Park", 21.280191, -157.829852, 100.9),
    ("kalakaua-019", "Fort DeRussy Beach Park", 21.280101, -157.829795, 102.7),
    ("kalakaua-020", "Fort DeRussy Beach Park", 21.280018, -157.829741, 104.3),
    ("kalakaua-021", "Fort DeRussy Beach Park", 21.279869, -157.829636, 107.3),
    ("kalakaua-022", "Fort DeRussy Beach Park", 21.279458, -157.829302, 115.8),
    ("kalakaua-023", "Fort DeRussy Beach Park", 21.279399, -157.829255, 117.0),
    ("kalakaua-024", "Fort DeRussy Beach Park", 21.279369, -157.829225, 117.7),
    ("kalakaua-025", "Fort DeRussy Beach Park", 21.278987, -157.828818, 126.6),
    ("kalakaua-026", "Fort DeRussy Beach Park", 21.278738, -157.828553, 132.5),
    ("kalakaua-027", "Royal Hawaiian Center", 21.278190, -157.827931, 145.7),
    ("kalakaua-028", "Royal Hawaiian Center", 21.278049, -157.827773, 149.1),
    ("kalakaua-029", "Royal Hawaiian Center", 21.277658, -157.827328, 158.5),
    ("kalakaua-030", "Royal Hawaiian Center", 21.277507, -157.827157, 162.2),
    ("kalakaua-031", "Moana Surfrider", 21.276922, -157.826503, 176.2),
    ("kalakaua-032", "Moana Surfrider", 21.276729, -157.826291, 180.8),
    ("kalakaua-033", "Moana Surfrider", 21.276539, -157.826079, 185.3),
    ("kalakaua-034", "Moana Surfrider", 21.276108, -157.825644, 195.2),
    ("kalakaua-035", "Duke Kahanamoku Statue", 21.275358, -157.824953, 211.6),
    ("kalakaua-036", "Duke Kahanamoku Statue", 21.275292, -157.824883, 213.1),
    ("kalakaua-037", "Duke Kahanamoku Statue", 21.275125, -157.824703, 217.0),
    ("kalakaua-038", "Duke Kahanamoku Statue", 21.275014, -157.824620, 219.3),
    ("kalakaua-039", "Duke Kahanamoku Statue", 21.274924, -157.824553, 221.1),
    ("kalakaua-040", "Duke Kahanamoku Statue", 21.274686, -157.824417, 225.6),
    ("kalakaua-041", "Duke Kahanamoku Statue", 21.274628, -157.824390, 226.6),
    ("kalakaua-042", "Duke Kahanamoku Statue", 21.274434, -157.824289, 230.2),
    ("kalakaua-043", "Duke Kahanamoku Statue", 21.273903, -157.823990, 240.1),
    ("kalakaua-044", "Kuhio Beach", 21.273105, -157.823584, 254.8),
    ("kalakaua-045", "Kuhio Beach", 21.272311, -157.823154, 269.6),
    ("kalakaua-046", "Kalakaua Avenue at Kapahulu Avenue", 21.271505, -157.822757, 284.3),
]


def main() -> None:
    facts = dedupe_facts([normalize_fact(fact) for fact in KALAKAUA_WAIKIKI_FACTS])
    ids = [fact["id"] for fact in facts]
    if len(facts) < 25:
        raise SystemExit(f"Need at least 25 strict Kalakaua/Waikiki facts, found {len(facts)}")
    if len(ids) != len(set(ids)):
        raise SystemExit("Fact ids must be unique")

    RESOURCE_DIR.mkdir(parents=True, exist_ok=True)
    facts_path = RESOURCE_DIR / "HonoluluFacts.json"
    review_path = RESOURCE_DIR / "HonoluluFactsReview.csv"
    route_path = RESOURCE_DIR / "HonoluluRoute.json"

    facts_path.write_text(json.dumps(facts, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    write_review_csv(facts, review_path)
    route_payload = [
        {
            "id": item[0],
            "label": item[1],
            "latitude": item[2],
            "longitude": item[3],
            "secondsFromStart": item[4],
        }
        for item in ROUTE
    ]
    route_path.write_text(json.dumps(route_payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    print(f"Wrote {len(facts)} facts to {facts_path}")
    print(f"Wrote review CSV to {review_path}")
    print(f"Wrote {len(route_payload)} route waypoints to {route_path}")


if __name__ == "__main__":
    main()
