#!/usr/bin/env python3
"""Generate the bundled Honolulu route and local context pack for Cruisin."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RESOURCE_DIR = ROOT / "Cruisin"


FACTS = [
    {
        "id": "area-waikiki",
        "name": "Waikiki",
        "category": "area",
        "latitude": 21.2793,
        "longitude": -157.8293,
        "narration": "You are entering Waikiki, the dense beachfront district that turned Honolulu into a global visitor hub.",
        "sourceName": "Wikipedia",
        "sourceURL": "https://en.wikipedia.org/wiki/Waikiki",
        "priority": 5,
    },
    {
        "id": "poi-duke-kahanamoku-statue",
        "name": "Duke Kahanamoku Statue",
        "category": "culture",
        "latitude": 21.2767,
        "longitude": -157.8257,
        "narration": "The Duke Kahanamoku statue honors the Olympic swimmer and surfer who helped introduce modern surfing to the world.",
        "sourceName": "Go Hawaii",
        "sourceURL": "https://www.gohawaii.com/islands/oahu/regions/honolulu/duke-kahanamoku-statue",
        "priority": 5,
    },
    {
        "id": "poi-waikiki-beach",
        "name": "Waikiki Beach",
        "category": "landmark",
        "latitude": 21.2766,
        "longitude": -157.8268,
        "narration": "Waikiki Beach is a short, famous sweep of sand backed by hotels, surf breaks, and Diamond Head views.",
        "sourceName": "Wikipedia",
        "sourceURL": "https://en.wikipedia.org/wiki/Waikiki_Beach",
        "priority": 5,
    },
    {
        "id": "poi-moana-surfrider",
        "name": "Moana Surfrider",
        "category": "history",
        "latitude": 21.2769,
        "longitude": -157.8278,
        "narration": "The Moana Surfrider opened in 1901 and is often called the First Lady of Waikiki.",
        "sourceName": "Historic Hotels of America",
        "sourceURL": "https://www.historichotels.org/us/hotels-resorts/moana-surfrider-a-westin-resort-and-spa/",
        "priority": 4,
    },
    {
        "id": "poi-royal-hawaiian-hotel",
        "name": "Royal Hawaiian Hotel",
        "category": "history",
        "latitude": 21.2776,
        "longitude": -157.8296,
        "narration": "The pink Royal Hawaiian Hotel opened in 1927 and became one of Waikiki's most recognizable landmarks.",
        "sourceName": "Wikipedia",
        "sourceURL": "https://en.wikipedia.org/wiki/Royal_Hawaiian_Hotel",
        "priority": 4,
    },
    {
        "id": "poi-international-market-place",
        "name": "International Market Place",
        "category": "landmark",
        "latitude": 21.2794,
        "longitude": -157.8267,
        "narration": "International Market Place sits around a large banyan tree and marks a long-running retail crossroads in Waikiki.",
        "sourceName": "International Market Place",
        "sourceURL": "https://shopinternationalmarketplace.com/",
        "priority": 3,
    },
    {
        "id": "poi-honolulu-zoo",
        "name": "Honolulu Zoo",
        "category": "nature",
        "latitude": 21.2715,
        "longitude": -157.8213,
        "narration": "Honolulu Zoo anchors the Diamond Head end of Waikiki near Kapiolani Park.",
        "sourceName": "Honolulu Zoo",
        "sourceURL": "https://www.honoluluzoo.org/",
        "priority": 3,
    },
    {
        "id": "poi-kapiolani-park",
        "name": "Kapiolani Park",
        "category": "nature",
        "latitude": 21.2686,
        "longitude": -157.8193,
        "narration": "Kapiolani Park is Honolulu's oldest public park and a green buffer between Waikiki and Diamond Head.",
        "sourceName": "City and County of Honolulu",
        "sourceURL": "https://www.honolulu.gov/parks/",
        "priority": 3,
    },
    {
        "id": "poi-waikiki-aquarium",
        "name": "Waikiki Aquarium",
        "category": "nature",
        "latitude": 21.2657,
        "longitude": -157.8213,
        "narration": "Waikiki Aquarium has focused on Pacific marine life beside the reef since the early twentieth century.",
        "sourceName": "Waikiki Aquarium",
        "sourceURL": "https://www.waikikiaquarium.org/",
        "priority": 3,
    },
    {
        "id": "poi-diamond-head",
        "name": "Diamond Head",
        "category": "lookout",
        "latitude": 21.2619,
        "longitude": -157.8059,
        "narration": "Diamond Head is the volcanic tuff cone framing Waikiki's eastern skyline.",
        "sourceName": "Hawaii State Parks",
        "sourceURL": "https://dlnr.hawaii.gov/dsp/parks/oahu/diamond-head-state-monument/",
        "priority": 5,
    },
    {
        "id": "poi-ala-wai-canal",
        "name": "Ala Wai Canal",
        "category": "landmark",
        "latitude": 21.2875,
        "longitude": -157.8346,
        "narration": "The Ala Wai Canal separates Waikiki from inland Honolulu and reshaped this former wetland district.",
        "sourceName": "Wikipedia",
        "sourceURL": "https://en.wikipedia.org/wiki/Ala_Wai_Canal",
        "priority": 4,
    },
    {
        "id": "poi-fort-derussy",
        "name": "Fort DeRussy",
        "category": "history",
        "latitude": 21.2799,
        "longitude": -157.8349,
        "narration": "Fort DeRussy is a military reservation and beach park that preserves a rare open stretch inside Waikiki.",
        "sourceName": "Wikipedia",
        "sourceURL": "https://en.wikipedia.org/wiki/Fort_DeRussy",
        "priority": 3,
    },
    {
        "id": "poi-army-museum-hawaii",
        "name": "U.S. Army Museum of Hawaii",
        "category": "history",
        "latitude": 21.2785,
        "longitude": -157.8336,
        "narration": "The U.S. Army Museum of Hawaii occupies Battery Randolph at Fort DeRussy.",
        "sourceName": "U.S. Army Museum of Hawaii",
        "sourceURL": "https://hiarmymuseumsoc.org/",
        "priority": 3,
    },
    {
        "id": "poi-hawaii-convention-center",
        "name": "Hawaii Convention Center",
        "category": "landmark",
        "latitude": 21.2901,
        "longitude": -157.8355,
        "narration": "The Hawaii Convention Center uses open-air architecture to catch trade winds near the edge of Waikiki.",
        "sourceName": "Hawaii Convention Center",
        "sourceURL": "https://www.hawaiiconvention.com/",
        "priority": 3,
    },
    {
        "id": "area-ala-moana",
        "name": "Ala Moana",
        "category": "area",
        "latitude": 21.2902,
        "longitude": -157.8436,
        "narration": "Ala Moana means path to the sea, and this district links shopping, beach park, and harbor edges.",
        "sourceName": "Wikipedia",
        "sourceURL": "https://en.wikipedia.org/wiki/Ala_Moana",
        "priority": 5,
    },
    {
        "id": "poi-ala-moana-center",
        "name": "Ala Moana Center",
        "category": "landmark",
        "latitude": 21.2915,
        "longitude": -157.8430,
        "narration": "Ala Moana Center is one of the world's largest open-air shopping centers.",
        "sourceName": "Ala Moana Center",
        "sourceURL": "https://www.alamoanacenter.com/",
        "priority": 4,
    },
    {
        "id": "poi-ala-moana-beach-park",
        "name": "Ala Moana Beach Park",
        "category": "nature",
        "latitude": 21.2849,
        "longitude": -157.8466,
        "narration": "Ala Moana Beach Park is a local favorite with calm water protected by an outer reef.",
        "sourceName": "City and County of Honolulu",
        "sourceURL": "https://www.honolulu.gov/parks/",
        "priority": 4,
    },
    {
        "id": "poi-magic-island",
        "name": "Magic Island",
        "category": "lookout",
        "latitude": 21.2842,
        "longitude": -157.8475,
        "narration": "Magic Island is a man-made peninsula with wide views back toward Waikiki and Diamond Head.",
        "sourceName": "Wikipedia",
        "sourceURL": "https://en.wikipedia.org/wiki/Magic_Island_(Hawaii)",
        "priority": 4,
    },
    {
        "id": "poi-yacht-harbor",
        "name": "Ala Wai Small Boat Harbor",
        "category": "landmark",
        "latitude": 21.2836,
        "longitude": -157.8395,
        "narration": "Ala Wai Small Boat Harbor sits between Waikiki and Ala Moana with one of Honolulu's busiest marina edges.",
        "sourceName": "Hawaii Division of Boating and Ocean Recreation",
        "sourceURL": "https://dlnr.hawaii.gov/dobor/ala-wai-small-boat-harbor/",
        "priority": 3,
    },
    {
        "id": "area-kakaako",
        "name": "Kakaako",
        "category": "area",
        "latitude": 21.2983,
        "longitude": -157.8576,
        "narration": "You are entering Kakaako, a former industrial district now known for murals, towers, restaurants, and waterfront parks.",
        "sourceName": "Wikipedia",
        "sourceURL": "https://en.wikipedia.org/wiki/Kaka%CA%BBako",
        "priority": 5,
    },
    {
        "id": "poi-ward-village",
        "name": "Ward Village",
        "category": "landmark",
        "latitude": 21.2947,
        "longitude": -157.8527,
        "narration": "Ward Village is a large mixed-use redevelopment reshaping the center of Kakaako.",
        "sourceName": "Ward Village",
        "sourceURL": "https://www.wardvillage.com/",
        "priority": 3,
    },
    {
        "id": "poi-salt-kakaako",
        "name": "SALT at Our Kakaako",
        "category": "food",
        "latitude": 21.2972,
        "longitude": -157.8610,
        "narration": "SALT at Our Kakaako clusters local food, coffee, shops, and public art in converted warehouse blocks.",
        "sourceName": "SALT at Our Kakaako",
        "sourceURL": "https://saltatkakaako.com/",
        "priority": 4,
    },
    {
        "id": "poi-kakaako-waterfront-park",
        "name": "Kakaako Waterfront Park",
        "category": "lookout",
        "latitude": 21.2951,
        "longitude": -157.8680,
        "narration": "Kakaako Waterfront Park has grassy hills and broad harbor views where industrial Honolulu meets the ocean.",
        "sourceName": "Hawaii Community Development Authority",
        "sourceURL": "https://dbedt.hawaii.gov/hcda/",
        "priority": 4,
    },
    {
        "id": "poi-kewalo-basin",
        "name": "Kewalo Basin Harbor",
        "category": "landmark",
        "latitude": 21.2896,
        "longitude": -157.8585,
        "narration": "Kewalo Basin Harbor is a working harbor for tour boats and fishing vessels at the edge of Kakaako.",
        "sourceName": "Kewalo Harbor",
        "sourceURL": "https://www.kewaloharbor.com/",
        "priority": 3,
    },
    {
        "id": "poi-mother-waldron-park",
        "name": "Mother Waldron Neighborhood Park",
        "category": "nature",
        "latitude": 21.2976,
        "longitude": -157.8596,
        "narration": "Mother Waldron Park is a neighborhood green space tucked inside Kakaako's fast-changing street grid.",
        "sourceName": "City and County of Honolulu",
        "sourceURL": "https://www.honolulu.gov/parks/",
        "priority": 2,
    },
    {
        "id": "poi-hawaii-childrens-discovery-center",
        "name": "Hawaii Children's Discovery Center",
        "category": "culture",
        "latitude": 21.2928,
        "longitude": -157.8634,
        "narration": "The Hawaii Children's Discovery Center sits near the waterfront with hands-on exhibits for families.",
        "sourceName": "Hawaii Children's Discovery Center",
        "sourceURL": "https://discoverycenterhawaii.org/",
        "priority": 2,
    },
    {
        "id": "poi-honolulu-museum-of-art",
        "name": "Honolulu Museum of Art",
        "category": "culture",
        "latitude": 21.3046,
        "longitude": -157.8489,
        "narration": "Honolulu Museum of Art connects Asian, Pacific, European, and American collections in a compact campus.",
        "sourceName": "Honolulu Museum of Art",
        "sourceURL": "https://honolulumuseum.org/",
        "priority": 4,
    },
    {
        "id": "poi-thomas-square",
        "name": "Thomas Square",
        "category": "history",
        "latitude": 21.3047,
        "longitude": -157.8509,
        "narration": "Thomas Square commemorates the 1843 restoration of the Hawaiian Kingdom's sovereignty.",
        "sourceName": "Wikipedia",
        "sourceURL": "https://en.wikipedia.org/wiki/Thomas_Square",
        "priority": 4,
    },
    {
        "id": "poi-blaisdell-center",
        "name": "Neal S. Blaisdell Center",
        "category": "culture",
        "latitude": 21.3009,
        "longitude": -157.8508,
        "narration": "The Blaisdell Center is Honolulu's major arena, concert hall, and exhibition complex.",
        "sourceName": "Neal S. Blaisdell Center",
        "sourceURL": "https://blaisdellcenter.com/",
        "priority": 3,
    },
    {
        "id": "area-civic-center",
        "name": "Capitol District",
        "category": "area",
        "latitude": 21.3068,
        "longitude": -157.8576,
        "narration": "You are entering Honolulu's civic core, where the palace, capitol, courts, and city hall sit within a few blocks.",
        "sourceName": "Wikipedia",
        "sourceURL": "https://en.wikipedia.org/wiki/Hawaii_Capital_Historic_District",
        "priority": 5,
    },
    {
        "id": "poi-iolani-palace",
        "name": "Iolani Palace",
        "category": "history",
        "latitude": 21.3069,
        "longitude": -157.8583,
        "narration": "Iolani Palace was the royal residence of the Hawaiian Kingdom and is the only official royal palace in the United States.",
        "sourceName": "Iolani Palace",
        "sourceURL": "https://www.iolanipalace.org/",
        "priority": 5,
    },
    {
        "id": "poi-king-kamehameha-statue",
        "name": "King Kamehameha Statue",
        "category": "history",
        "latitude": 21.3055,
        "longitude": -157.8589,
        "narration": "The King Kamehameha statue stands in front of Aliiolani Hale facing Iolani Palace.",
        "sourceName": "Wikipedia",
        "sourceURL": "https://en.wikipedia.org/wiki/Statues_of_Kamehameha_I",
        "priority": 4,
    },
    {
        "id": "poi-aliiolani-hale",
        "name": "Aliiolani Hale",
        "category": "history",
        "latitude": 21.3054,
        "longitude": -157.8587,
        "narration": "Aliiolani Hale houses the Hawaii State Supreme Court and anchors one side of the palace grounds.",
        "sourceName": "Hawaii State Judiciary",
        "sourceURL": "https://www.courts.state.hi.us/",
        "priority": 4,
    },
    {
        "id": "poi-hawaii-state-capitol",
        "name": "Hawaii State Capitol",
        "category": "landmark",
        "latitude": 21.3075,
        "longitude": -157.8570,
        "narration": "The Hawaii State Capitol uses reflecting pools and open forms to reference the islands, ocean, and volcanoes.",
        "sourceName": "Wikipedia",
        "sourceURL": "https://en.wikipedia.org/wiki/Hawaii_State_Capitol",
        "priority": 4,
    },
    {
        "id": "poi-kawaiahao-church",
        "name": "Kawaiahao Church",
        "category": "history",
        "latitude": 21.3043,
        "longitude": -157.8595,
        "narration": "Kawaiahao Church was built from coral blocks and is closely tied to nineteenth-century Honolulu.",
        "sourceName": "Kawaiahao Church",
        "sourceURL": "https://www.kawaiahao.org/",
        "priority": 4,
    },
    {
        "id": "poi-honolulu-hale",
        "name": "Honolulu Hale",
        "category": "landmark",
        "latitude": 21.3047,
        "longitude": -157.8584,
        "narration": "Honolulu Hale is the city hall for the City and County of Honolulu.",
        "sourceName": "City and County of Honolulu",
        "sourceURL": "https://www.honolulu.gov/",
        "priority": 3,
    },
    {
        "id": "poi-hawaiian-mission-houses",
        "name": "Hawaiian Mission Houses",
        "category": "history",
        "latitude": 21.3041,
        "longitude": -157.8603,
        "narration": "The Hawaiian Mission Houses preserve some of Honolulu's oldest Western-style buildings.",
        "sourceName": "Hawaiian Mission Houses",
        "sourceURL": "https://missionhouses.org/",
        "priority": 3,
    },
    {
        "id": "poi-washington-place",
        "name": "Washington Place",
        "category": "history",
        "latitude": 21.3097,
        "longitude": -157.8570,
        "narration": "Washington Place was Queen Liliuokalani's home and later served as Hawaii's governor's residence.",
        "sourceName": "Washington Place Foundation",
        "sourceURL": "https://washingtonplacefoundation.org/",
        "priority": 3,
    },
    {
        "id": "poi-state-library",
        "name": "Hawaii State Library",
        "category": "culture",
        "latitude": 21.3062,
        "longitude": -157.8565,
        "narration": "The Hawaii State Library faces the capitol district from a historic Beaux-Arts building.",
        "sourceName": "Hawaii State Public Library System",
        "sourceURL": "https://www.librarieshawaii.org/branch/hawaii-state-library/",
        "priority": 2,
    },
    {
        "id": "poi-punchbowl",
        "name": "National Memorial Cemetery of the Pacific",
        "category": "lookout",
        "latitude": 21.3121,
        "longitude": -157.8466,
        "narration": "Punchbowl crater holds the National Memorial Cemetery of the Pacific and a sweeping view over Honolulu.",
        "sourceName": "National Cemetery Administration",
        "sourceURL": "https://www.cem.va.gov/cems/nchp/nmcp.asp",
        "priority": 4,
    },
    {
        "id": "poi-aloha-tower",
        "name": "Aloha Tower",
        "category": "history",
        "latitude": 21.3069,
        "longitude": -157.8657,
        "narration": "Aloha Tower opened in 1926 as a harbor landmark greeting passengers arriving by ship.",
        "sourceName": "Wikipedia",
        "sourceURL": "https://en.wikipedia.org/wiki/Aloha_Tower",
        "priority": 4,
    },
    {
        "id": "poi-honolulu-harbor",
        "name": "Honolulu Harbor",
        "category": "landmark",
        "latitude": 21.3061,
        "longitude": -157.8702,
        "narration": "Honolulu Harbor is the state's main commercial harbor and has shaped the city since the monarchy era.",
        "sourceName": "Hawaii Department of Transportation",
        "sourceURL": "https://hidot.hawaii.gov/harbors/",
        "priority": 3,
    },
    {
        "id": "area-chinatown",
        "name": "Chinatown",
        "category": "area",
        "latitude": 21.3114,
        "longitude": -157.8625,
        "narration": "You are entering Chinatown, one of Honolulu's oldest business districts and a dense food and arts neighborhood.",
        "sourceName": "Wikipedia",
        "sourceURL": "https://en.wikipedia.org/wiki/Chinatown,_Honolulu",
        "priority": 5,
    },
    {
        "id": "poi-hawaii-theatre",
        "name": "Hawaii Theatre",
        "category": "culture",
        "latitude": 21.3119,
        "longitude": -157.8623,
        "narration": "Hawaii Theatre opened in 1922 and remains a major restored performing arts venue downtown.",
        "sourceName": "Hawaii Theatre Center",
        "sourceURL": "https://www.hawaiitheatre.com/",
        "priority": 4,
    },
    {
        "id": "poi-foster-botanical-garden",
        "name": "Foster Botanical Garden",
        "category": "nature",
        "latitude": 21.3160,
        "longitude": -157.8587,
        "narration": "Foster Botanical Garden preserves tropical trees and plants in the middle of urban Honolulu.",
        "sourceName": "Honolulu Botanical Gardens",
        "sourceURL": "https://www.honolulu.gov/parks/hbg/",
        "priority": 3,
    },
    {
        "id": "poi-liliuokalani-botanical-garden",
        "name": "Liliuokalani Botanical Garden",
        "category": "nature",
        "latitude": 21.3187,
        "longitude": -157.8554,
        "narration": "Liliuokalani Botanical Garden focuses on native Hawaiian plants and a stream-fed urban landscape.",
        "sourceName": "Honolulu Botanical Gardens",
        "sourceURL": "https://www.honolulu.gov/parks/hbg/",
        "priority": 3,
    },
    {
        "id": "poi-murphy-bar",
        "name": "Murphy's Bar and Grill",
        "category": "food",
        "latitude": 21.3104,
        "longitude": -157.8623,
        "narration": "Murphy's occupies a historic downtown corner and is a familiar Chinatown-adjacent lunch and pau hana stop.",
        "sourceName": "Murphy's Bar and Grill",
        "sourceURL": "https://www.murphyshawaii.com/",
        "priority": 2,
    },
    {
        "id": "poi-the-pig-and-the-lady",
        "name": "The Pig and the Lady",
        "category": "food",
        "latitude": 21.3126,
        "longitude": -157.8618,
        "narration": "The Pig and the Lady helped make Chinatown a modern Honolulu dining destination.",
        "sourceName": "The Pig and the Lady",
        "sourceURL": "https://thepigandthelady.com/",
        "priority": 3,
    },
    {
        "id": "poi-maguro-brothers-chinatown",
        "name": "Maguro Brothers Chinatown",
        "category": "food",
        "latitude": 21.3125,
        "longitude": -157.8612,
        "narration": "Maguro Brothers is known for sashimi and poke from a small Chinatown market counter.",
        "sourceName": "Maguro Brothers Hawaii",
        "sourceURL": "https://www.magurobrothershawaii.com/",
        "priority": 2,
    },
    {
        "id": "poi-leonards-bakery",
        "name": "Leonard's Bakery",
        "category": "food",
        "latitude": 21.2849,
        "longitude": -157.8135,
        "narration": "Leonard's Bakery is famous for malasadas, the Portuguese-style doughnuts that became a Honolulu staple.",
        "sourceName": "Leonard's Bakery",
        "sourceURL": "https://www.leonardshawaii.com/",
        "priority": 3,
    },
    {
        "id": "poi-rainbow-drive-in",
        "name": "Rainbow Drive-In",
        "category": "food",
        "latitude": 21.2774,
        "longitude": -157.8134,
        "narration": "Rainbow Drive-In is a plate-lunch institution near the Diamond Head side of Waikiki.",
        "sourceName": "Rainbow Drive-In",
        "sourceURL": "https://rainbowdrivein.com/",
        "priority": 3,
    },
    {
        "id": "poi-marugame-udon-waikiki",
        "name": "Marugame Udon Waikiki",
        "category": "food",
        "latitude": 21.2796,
        "longitude": -157.8266,
        "narration": "Marugame Udon's Waikiki shop is known for fast cafeteria-style noodles and frequent lines.",
        "sourceName": "Marugame Udon USA",
        "sourceURL": "https://www.marugameudon.com/",
        "priority": 2,
    },
    {
        "id": "poi-liliha-bakery",
        "name": "Liliha Bakery",
        "category": "food",
        "latitude": 21.3167,
        "longitude": -157.8483,
        "narration": "Liliha Bakery is known for coco puffs and local diner comfort food.",
        "sourceName": "Liliha Bakery",
        "sourceURL": "https://www.lilihabakery.com/",
        "priority": 2,
    },
    {
        "id": "poi-highway-inn-kakaako",
        "name": "Highway Inn Kakaako",
        "category": "food",
        "latitude": 21.2973,
        "longitude": -157.8611,
        "narration": "Highway Inn's Kakaako location serves Hawaiian food in the middle of the neighborhood's restaurant cluster.",
        "sourceName": "Highway Inn",
        "sourceURL": "https://www.myhighwayinn.com/",
        "priority": 3,
    },
    {
        "id": "poi-side-street-inn",
        "name": "Side Street Inn",
        "category": "food",
        "latitude": 21.2956,
        "longitude": -157.8364,
        "narration": "Side Street Inn is a local comfort-food spot known for share plates and after-work gatherings.",
        "sourceName": "Side Street Inn",
        "sourceURL": "https://sidestreetinn.com/",
        "priority": 2,
    },
    {
        "id": "poi-bishop-museum",
        "name": "Bishop Museum",
        "category": "culture",
        "latitude": 21.3339,
        "longitude": -157.8708,
        "narration": "Bishop Museum is Hawaii's major museum for natural history and Hawaiian and Pacific culture.",
        "sourceName": "Bishop Museum",
        "sourceURL": "https://www.bishopmuseum.org/",
        "priority": 3,
    },
    {
        "id": "poi-queen-emma-summer-palace",
        "name": "Queen Emma Summer Palace",
        "category": "history",
        "latitude": 21.3665,
        "longitude": -157.7934,
        "narration": "Queen Emma Summer Palace preserves a mountain-side royal retreat above Honolulu.",
        "sourceName": "Daughters of Hawaii",
        "sourceURL": "https://daughtersofhawaii.org/",
        "priority": 2,
    },
    {
        "id": "poi-tantalus-lookout",
        "name": "Tantalus Lookout",
        "category": "lookout",
        "latitude": 21.3157,
        "longitude": -157.8180,
        "narration": "Tantalus Lookout gives a high, sweeping view over Diamond Head, Waikiki, downtown, and the harbor.",
        "sourceName": "Hawaii State Parks",
        "sourceURL": "https://dlnr.hawaii.gov/dsp/parks/oahu/puu-ualakaa-state-wayside/",
        "priority": 3,
    },
    {
        "id": "poi-manoa-falls",
        "name": "Manoa Falls Trail",
        "category": "nature",
        "latitude": 21.3330,
        "longitude": -157.8009,
        "narration": "Manoa Falls Trail leads through a rainforest valley to one of Honolulu's most visited waterfalls.",
        "sourceName": "Hawaii Trails",
        "sourceURL": "https://hawaiitrails.hawaii.gov/trails/",
        "priority": 2,
    },
    {
        "id": "poi-shangri-la",
        "name": "Shangri La Museum of Islamic Art",
        "category": "culture",
        "latitude": 21.2552,
        "longitude": -157.7872,
        "narration": "Shangri La is Doris Duke's oceanfront home and a museum of Islamic art near Diamond Head.",
        "sourceName": "Shangri La",
        "sourceURL": "https://www.shangrilahawaii.org/",
        "priority": 2,
    },
    {
        "id": "poi-sans-souci-beach",
        "name": "Sans Souci Beach",
        "category": "nature",
        "latitude": 21.2649,
        "longitude": -157.8204,
        "narration": "Sans Souci Beach is a calmer swimming and snorkeling pocket near the Waikiki Aquarium.",
        "sourceName": "City and County of Honolulu",
        "sourceURL": "https://www.honolulu.gov/parks/",
        "priority": 2,
    },
    {
        "id": "poi-royal-mausoleum",
        "name": "Royal Mausoleum at Mauna Ala",
        "category": "history",
        "latitude": 21.3263,
        "longitude": -157.8473,
        "narration": "Mauna Ala is the Royal Mausoleum, resting place for many members of Hawaiian royal families.",
        "sourceName": "Hawaii State Parks",
        "sourceURL": "https://dlnr.hawaii.gov/dsp/parks/oahu/royal-mausoleum-state-monument/",
        "priority": 2,
    },
    {
        "id": "poi-japanese-cultural-center",
        "name": "Japanese Cultural Center of Hawaii",
        "category": "culture",
        "latitude": 21.2941,
        "longitude": -157.8190,
        "narration": "The Japanese Cultural Center of Hawaii preserves stories of Japanese immigration and community life in the islands.",
        "sourceName": "Japanese Cultural Center of Hawaii",
        "sourceURL": "https://www.jcch.com/",
        "priority": 2,
    },
    {
        "id": "poi-university-hawaii-manoa",
        "name": "University of Hawaii at Manoa",
        "category": "landmark",
        "latitude": 21.2969,
        "longitude": -157.8171,
        "narration": "The University of Hawaii at Manoa sits in the valley behind Waikiki and is the flagship public university campus.",
        "sourceName": "University of Hawaii at Manoa",
        "sourceURL": "https://manoa.hawaii.edu/",
        "priority": 2,
    },
    {
        "id": "poi-chaminade-university",
        "name": "Chaminade University",
        "category": "landmark",
        "latitude": 21.2902,
        "longitude": -157.8079,
        "narration": "Chaminade University occupies a hillside campus above Kaimuki with broad views toward Honolulu.",
        "sourceName": "Chaminade University",
        "sourceURL": "https://chaminade.edu/",
        "priority": 1,
    },
]


ROUTE = [
    ("kalakaua-001", "Kalakaua Avenue at Ala Moana Boulevard", 21.285546, -157.832941, 0.0),
    ("kalakaua-002", "Kalakaua Avenue at Ala Moana Boulevard", 21.284828, -157.832516, 13.6),
    ("kalakaua-003", "Kalakaua Avenue at Ala Moana Boulevard", 21.284613, -157.832371, 17.8),
    ("kalakaua-004", "Kalakaua Avenue at Ala Moana Boulevard", 21.284247, -157.832118, 25.0),
    ("kalakaua-005", "Kalakaua Avenue at Ala Moana Boulevard", 21.284028, -157.831980, 29.3),
    ("kalakaua-006", "Kalakaua Avenue at Ala Moana Boulevard", 21.283881, -157.831896, 32.0),
    ("kalakaua-007", "Kalakaua Avenue at Ala Moana Boulevard", 21.283747, -157.831820, 34.5),
    ("kalakaua-008", "Kalakaua Avenue at Ala Moana Boulevard", 21.283654, -157.831767, 36.3),
    ("kalakaua-009", "Kalakaua Avenue at Ala Moana Boulevard", 21.283304, -157.831569, 42.9),
    ("kalakaua-010", "Waikiki Gateway", 21.283051, -157.831425, 47.6),
    ("kalakaua-011", "Waikiki Gateway", 21.282907, -157.831343, 50.3),
    ("kalakaua-012", "Waikiki Gateway", 21.282423, -157.831089, 59.3),
    ("kalakaua-013", "Waikiki Gateway", 21.282324, -157.831038, 61.1),
    ("kalakaua-014", "Waikiki Gateway", 21.281903, -157.830814, 68.9),
    ("kalakaua-015", "Waikiki Gateway", 21.281876, -157.830800, 69.4),
    ("kalakaua-016", "Waikiki Gateway", 21.281491, -157.830590, 76.5),
    ("kalakaua-017", "Waikiki Gateway", 21.281288, -157.830474, 80.4),
    ("kalakaua-018", "Fort DeRussy Beach Park", 21.280191, -157.829852, 100.9),
    ("kalakaua-019", "Fort DeRussy Beach Park", 21.280101, -157.829795, 102.7),
    ("kalakaua-020", "Fort DeRussy Beach Park", 21.280018, -157.829741, 104.3),
    ("kalakaua-021", "Fort DeRussy Beach Park", 21.279869, -157.829636, 107.3),
    ("kalakaua-022", "Fort DeRussy Beach Park", 21.279458, -157.829302, 115.8),
    ("kalakaua-023", "Fort DeRussy Beach Park", 21.279399, -157.829255, 117.0),
    ("kalakaua-024", "Fort DeRussy Beach Park", 21.279369, -157.829225, 117.7),
    ("kalakaua-025", "Fort DeRussy Beach Park", 21.278987, -157.828818, 126.6),
    ("kalakaua-026", "Fort DeRussy Beach Park", 21.278738, -157.828553, 132.5),
    ("kalakaua-027", "Royal Hawaiian Center", 21.278190, -157.827931, 145.7),
    ("kalakaua-028", "Royal Hawaiian Center", 21.278049, -157.827773, 149.1),
    ("kalakaua-029", "Royal Hawaiian Center", 21.277658, -157.827328, 158.5),
    ("kalakaua-030", "Royal Hawaiian Center", 21.277507, -157.827157, 162.2),
    ("kalakaua-031", "Moana Surfrider", 21.276922, -157.826503, 176.2),
    ("kalakaua-032", "Moana Surfrider", 21.276729, -157.826291, 180.8),
    ("kalakaua-033", "Moana Surfrider", 21.276539, -157.826079, 185.3),
    ("kalakaua-034", "Moana Surfrider", 21.276108, -157.825644, 195.2),
    ("kalakaua-035", "Duke Kahanamoku Statue", 21.275358, -157.824953, 211.6),
    ("kalakaua-036", "Duke Kahanamoku Statue", 21.275292, -157.824883, 213.1),
    ("kalakaua-037", "Duke Kahanamoku Statue", 21.275125, -157.824703, 217.0),
    ("kalakaua-038", "Duke Kahanamoku Statue", 21.275014, -157.824620, 219.3),
    ("kalakaua-039", "Duke Kahanamoku Statue", 21.274924, -157.824553, 221.1),
    ("kalakaua-040", "Duke Kahanamoku Statue", 21.274686, -157.824417, 225.6),
    ("kalakaua-041", "Duke Kahanamoku Statue", 21.274628, -157.824390, 226.6),
    ("kalakaua-042", "Duke Kahanamoku Statue", 21.274434, -157.824289, 230.2),
    ("kalakaua-043", "Duke Kahanamoku Statue", 21.273903, -157.823990, 240.1),
    ("kalakaua-044", "Kuhio Beach", 21.273105, -157.823584, 254.8),
    ("kalakaua-045", "Kuhio Beach", 21.272311, -157.823154, 269.6),
    ("kalakaua-046", "Kalakaua Avenue at Kapahulu Avenue", 21.271505, -157.822757, 284.3),
]


def main() -> None:
    ids = [fact["id"] for fact in FACTS]
    if len(FACTS) < 50:
        raise SystemExit(f"Need at least 50 facts, found {len(FACTS)}")
    if len(ids) != len(set(ids)):
        raise SystemExit("Fact ids must be unique")

    RESOURCE_DIR.mkdir(parents=True, exist_ok=True)
    facts_path = RESOURCE_DIR / "HonoluluFacts.json"
    route_path = RESOURCE_DIR / "HonoluluRoute.json"

    facts_path.write_text(json.dumps(FACTS, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    route_payload = [
        {
            "id": item[0],
            "label": item[1],
            "latitude": item[2],
            "longitude": item[3],
            "secondsFromStart": item[4],
        }
        for item in ROUTE
    ]
    route_path.write_text(json.dumps(route_payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    print(f"Wrote {len(FACTS)} facts to {facts_path}")
    print(f"Wrote {len(route_payload)} route waypoints to {route_path}")


if __name__ == "__main__":
    main()
